### ISSUE TITLE
On fresh install, `elm-app start` won't run template project

### ISSUE THREAD

**Issue by undreren** [halfzebra/create-elm-app#10]
Even though the README.md states that there should be generated a elm-package.json, none is generated. It is not present in the /template sub-directory in the create-elm-app repository.

**Comment by joakin** [comment]
```
tests $ create-elm-app cea-elm-test

Creating cea-elm-test project...

Starting downloads...

  ● elm-lang/virtual-dom 1.1.1
  ● elm-lang/html 1.1.0
  ● elm-lang/core 4.0.5

Packages configured successfully!

Project is successfully created in `/Users/jhernandez/dev/tests/cea-elm-test`.
tests $ cd cea-elm-test/
cea-elm-test $ t
.
├── README.md
├── elm-package.json
├── elm-stuff
└── src

2 directories, 2 files
```

This just worked for me, can you provide more details?

**Comment by jackysee** [comment]
I have the same problem, `elm-package.json` is not generated. The downloading part is missing.

```
jacky $ create-elm-app myapp

Creating myapp project...


Project is successfully created in `/Users/jacky/myapp`.
jacky$ cd myapp
jacky$ ls -al
total 16
drwxr-xr-x  5 jacky  staff   170 Sep 22 22:48 .
drwxr-xr-x  3 jacky  staff   102 Sep 22 22:48 ..
-rw-r--r--  1 jacky  staff   186 Sep 22 22:48 .gitignore
-rw-r--r--  1 jacky  staff  3874 Sep 22 22:48 README.md
drwxr-xr-x  7 jacky  staff   238 Sep 22 22:48 src

```

using node 4.4.7

**Comment by joakin** [comment]
BTW, my (working) setup was osx 10.11, node 6.5, npm 3.10, and I have the
elm platform installed from homebrew globally.

**Comment by undreren** [comment]
I get the same console dump. I'm running Ubuntu 16.04.

**Comment by undreren** [comment]
I found a fix with the help of @halfzebra. It turns out that the `elm` module in the path

`/usr/local/lib/node_modules/create-elm-app/node_modules/elm`

hadn't been installed. Running `sudo npm run install` in this directory fixed all my problems.

**Comment by Coder-Kev** [comment]
Microsoft Windows 7 Pro results in same error.

C:\course\Start_Up_with_Elm_App>create-elm-app my-app
Creating my-app project...
Failed to install elm packages
Please, make sure you have internet connection!
In case if you are running Unix OS, you might look in to this issue:
    https://github.com/halfzebra/create-elm-app/issues/10

**Comment by rmeshksar** [comment]
Hi,
I am having this problem on Windows 10. Tried the suggestions but none of them worked.

I would appreciate our help.

**Comment by halfzebra** [comment]
Hello @rmeshksar!

Thanks for the feedback, it would be helpful if you could create a new issue with all possible info that will help us help you 🙂

**Comment by rikvdkleij** [comment]
Same problem here on Ubuntu, getting a bit desperate after trying so many solutions with using `npm`.

**Comment by rikvdkleij** [comment]
Latest state is that I have configured `npm` in a way that packages are installed in my home directory in `.npm-global` because I was keeping permissions problems.

I cloned this project, run `npm install -g` in project folder. When creating a new app with `create-elm-app`, I get the error 
```
Creating xxx project...

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/rik/elmprojects/create-elm-app/node_modules/elm/unpacked_bin/elm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Failed to install elm packages

Please, make sure you have internet connection!

In case if you are running Unix OS, you might look in to this issue:

    https://github.com/halfzebra/create-elm-app/issues/10


```

**Comment by rikvdkleij** [comment]
Finally fixed it by setting the permissions right for the whole `.npm_global` folder (for some reason a `node_modules` was owned by root.

Then running `sudo npm run install` fixed the problem.

**Comment by turboMaCk** [comment]
@rikvdkleij please never use `sudo` with npm. Npm install can perform changes on FS and other things (using `scripts`) and running it with sudo gives it control over your whole system.

Setup your npm to use directory which doesn't require root for write.

```
$ mkdir -p $HOME/.npm-global
$ npm config set prefix $HOME/.npm-global
```

**Comment by psiphi75** [comment]
To add to @turboMaCk's point, the following additional command will add the `$HOME/.npm-global` to your path such that `create-elm-app` just works.  Works for bash, modify for other shells.

```
$ mkdir -p $HOME/.npm-global
$ npm config set prefix $HOME/.npm-global
$ echo 'PATH=$PATH:$HOME/.npm-global/bin' >> $HOME/.bashrc
```
