### ISSUE TITLE
Allow use of project-local webpack.config.js files

### ISSUE THREAD

**Issue by pzingg** [halfzebra/create-elm-app#100]
I was struggling with more than a few issues due to bizarre relative URL loading results from bootstrap.css files that were built into my Elm project, as well as having to have a `node` config option to get a required node module to go into the build.

After a few hours of tinkering I got things working, and also added some niceties using the CopyWebpackPlugin to move some files into our dist folder when doing an `elm-app build`.  I was wondering whether there's any easy fix for create-elm-app to have it look in a `config` folder right under the current Elm project root **first** for a config file, and if it can't find one, then go to the one thats installed globally (usually at '/usr/local/lib/node_modules/create-elm-app/config`).

Right now I'm forced to copy my webpack configs to overwrite those global ones.

**Comment by Lodin** [comment]
Did you try the `elm-app eject` command?

**Comment by halfzebra** [comment]
@pzingg It took a while to get there, but the latest release enables you to have statically served content outside the module system. 🎉 

Check it out.

Create Elm App not allow local `webpack.config` files, I'm afraid this will introduce too much complexity to the project.
