### ISSUE TITLE
yarn is still not working

### ISSUE THREAD

**Issue by gyzerok** [halfzebra/create-elm-app#102]
### Reproduce

```
yarn global add create-elm-app
elm-app create test
cd test
elm-app start
```

![screen shot 2017-03-02 at 16 19 29](https://cloud.githubusercontent.com/assets/1706020/23510978/4faf6658-ff64-11e6-90be-e8a5a5974c61.png)

**Comment by halfzebra** [comment]
@gyzerok I've got some progress on that one, I hope to fix this in the next release.
