### ISSUE TITLE
How to handle assets path?

### ISSUE THREAD

**Issue by lili21** [halfzebra/create-elm-app#106]
like image ?

**Comment by halfzebra** [comment]
@lili21 check out the [index.js](https://github.com/halfzebra/create-elm-app/blob/aeedd28c4c082a1a31c70e113fa0193a8c1c0ae9/template/src/index.js), it features the example of including the svg file into the application.

**Comment by joanllenas** [comment]
In my project, I needed to copy some assets into the dist folder so I ended up ejecting and adding the `CopyWebpackPlugin` to the webpack config js files.
It would be nice to have some cli support for that.

**Comment by halfzebra** [comment]
Since #143, [User Guide](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#adding-images-and-fonts) covers a couple ways of managing assets.

I hope it helps, if not, please feel free to reopen this issue! 🤞
