### ISSUE TITLE
Can't Deploy dist to Github Pages

### ISSUE THREAD

**Issue by tmountain** [halfzebra/create-elm-app#107]
I'm trying to do this:

`git subtree push --prefix dist origin gh-pages`

The issue is that Github pages is served via a directory off the hostname (i.e., https://tmountain.github.io/slide-deck/). All of the CSS and JS paths generated by webpack are absolute instead of relative  (i.e., /css/main.94015052.css), so they don't resolve properly.

Is there a way to generate these in a relative fashion to allow an easy deploy to Github pages?

**Comment by kkazuo** [comment]
I think this (https://github.com/halfzebra/create-elm-app/commit/8b775c3d) is the problem.

using  the previous version will fix.
```
npm install -g create-elm-app@0.2.3
```

**Comment by halfzebra** [comment]
@tmountain @kkazuo
[Deploying to GitHub Pages](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#deploying-to-github-pages) is now possible!

Thanks for contributing!
