### ISSUE TITLE
Start using correct semver notation

### ISSUE THREAD

**Issue by fobos** [halfzebra/create-elm-app#112]
@halfzebra What you think about releasing `v1.0.0` of the package? 
I think packages public API is enough stable and since `v1.0.0` we can use semver at full force

**Comment by halfzebra** [comment]
@fobos totally agree, just need to figure out the workaround for tricking the Semantic Release into bumping the [major version](https://github.com/semantic-release/semantic-release#major-breaking-release) 😄

**Comment by halfzebra** [comment]
`1.0.0` has landed 🎉
