### ISSUE TITLE
live reload on multiple files not workin in version 0.4.0

### ISSUE THREAD

**Issue by EvertYipYip** [halfzebra/create-elm-app#113]
In version 0.3.2 live reload worked if you had multiple files
for example:
- App.elm
- Main.elm
- Model.elm
- View.elm

Version 0.3.2 watched all files and when changes where made live recompiled, version 0.4.0 only watches the file with filename Main.elm

elm -v 0.18.0
node -v 6.9.1

**Comment by halfzebra** [comment]
@EvertYipYip Thanks for contributing!

Please give a shot to the latest version, I have fixed this issue! 🎉
