### ISSUE TITLE
New apps broken: Cannot read property 'embed' of undefined

### ISSUE THREAD

**Issue by roaks3** [halfzebra/create-elm-app#114]
I was getting this error in Chrome after creating a new app and running `elm-app start`:
`Uncaught TypeError: Cannot read property 'embed' of undefined`

It appears that due to some name changes, `Elm.Main.embed(root, logoPath)` should now be `Elm.App.embed(root, logoPath)`: https://github.com/halfzebra/create-elm-app/blob/master/template/src/index.js#L7

**Comment by fobos** [comment]
Ooops. Seems that in #110 I forgot rename it. Making a fix now
