### ISSUE TITLE
Favicon not changing in IE 11

### ISSUE THREAD

**Issue by freking** [halfzebra/create-elm-app#116]
I changed favicon.ico file and restarted the elm-app, but in Internet Explorer 11 the original Elm icon is still displayed.  I tried to adding <link rel="shortcut icon" href="/favicon.ico"> to the index.html file and it still doesn't update the favicon.

**Comment by fobos** [comment]
Looks like browser cache

**Comment by freking** [comment]
It's more than just the browser cache. I have deleted the browser history and refreshed the page and it still doesn't refresh the favicon.ico.  It works fine in Chrome and Firefox so it looks like this is an issue with how  IE handles and stores the favicon.

**Comment by fobos** [comment]
@freking Is the problem solved?

**Comment by halfzebra** [comment]
@freking I'm afraid the issue you're experiencing is not directly related to the Create Elm App project.

IE browsers have infamously aggressive favicon caching, please have a look at the existing ways to [force a favicon refresh](http://stackoverflow.com/questions/2208933/how-do-i-force-a-favicon-refresh/24166149#24166149)

I'm closing the issue, please feel free to reopen it if there's something wrong with the tool itself 🙂
