### ISSUE TITLE
Support CNAME in build process

### ISSUE THREAD

**Issue by newswim** [halfzebra/create-elm-app#118]
If you're using the `gh-pages` module as recommended in the readme, the /dist folder will not contain a CNAME file, even if there is one included in /src.

Gatsby.js was able to [work around this](https://github.com/gatsbyjs/gatsby/issues/6) by adding the file in /public, however this [webpack.config.js](https://github.com/halfzebra/create-elm-app/blob/master/config/webpack.config.prod.js) doesn't look for anything in that folder... honestly I'm not sure of how to add this to the webpack config, but that seems to be the best option.

One more option would be adding a `CNAME=www.website.com` record to `.env` and adding a step with [another plugin that generates a CNAME file](https://github.com/lozinsky/cname-webpack-plugin).

**Comment by halfzebra** [comment]
Hi @newswim!

I'm closing this issue because the latest release introduces `public/` folder, which you might use for this purpose. 🎉

**Comment by newswim** [comment]
Cool! Thank you!!!!
