### ISSUE TITLE
Document how to use npm JS libraries

### ISSUE THREAD

**Issue by joakin** [halfzebra/create-elm-app#12]
Hi!

First, this is an awesome tool, thanks a lot ❤️

Given this uses webpack it is very easy to use browser libraries in the JS files.

Maybe it would be useful to show how to use npm libraries for your JS code:

Example:
```sh
# Add package.json
npm init -y
# Install library from npm
npm install --save-dev xtend
# Use xtend in your JS code
```
```js
var xtend = require('xtend')
console.log(
  xtend({a: 1}, {b: 2}, {a: 3, c: 4})
)
```

Maybe after https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#installing-elm-packages in a section titled *Installing npm JS libraries*

Would you be interested in a PR?

Thanks again for your work on this.

**Comment by halfzebra** [comment]
Hello!

Thank you for your contribution, I like the idea 👍 

You are very welcome to work on a PR!
