### ISSUE TITLE
Installing packages for tests

### ISSUE THREAD

**Issue by shuhei** [halfzebra/create-elm-app#120]
By only reading README, It's not very obvious that we need to install packages also in the `tests` directory in addition to the project root.

It would be great if `elm-app package install xxx` installs packages also in the `tests` dir, or at least it's documented in the README template.

**Comment by shuhei** [comment]
Related to https://github.com/halfzebra/create-elm-app/issues/72

**Comment by shuhei** [comment]
@halfzwbra What do you think about automatically installing packages also in tests dir? If you think it's good, I'll make a pull request.

**Comment by halfzebra** [comment]
@shuhei Hello!

Thanks for contributing to Create Elm App!

It is indeed a good idea!

Luckily for us [rtfeldman/node-test-runner](https://github.com/rtfeldman/node-test-runner) already supports `--add-dependencies` flag, which [synchronizes the dependencies](https://github.com/rtfeldman/node-test-runner/pull/107) with the main `elm-package.json`

Maybe adding that flag to `elm-app test` would suffice?

It is also an option to mention this feature in the docs(as the cheapest way)

Please share your thoughts!

**Comment by shuhei** [comment]
@halfzebra It's a good idea to use `--add-dependencies`! However, it's not in 0.18.2, the current stable version, but in 0.18.3-beta3.

Maybe we can mention the pitfall while waiting for 0.18.3 to be released.
