### ISSUE TITLE
ES6 support on the JS bit

### ISSUE THREAD

**Issue by joshua1** [halfzebra/create-elm-app#122]
Hi @halfzebra , Is there some way to extend the build config to handle code written in ES6. I did modify the index.js file to have 
```
import './main.css';
const logoPath = require('./logo.svg');
const Elm = require('./Main.elm');

const root = document.getElementById('root');

Elm.Main.embed(root, logoPath);
```
And it threw the ``` unexpected token import ``` error  
babel-loader webpack plugin and es2015 presets should do this. i would rather it is in the webpack config than having to eject

**Comment by halfzebra** [comment]
@joshua1 Hello and thank you for the contribution!

I was considering adding ES6 support for a long time, I'm pretty open to the idea.

Would you like to work on the PR?

@jackfranklin @gyzerok @fobos got an opinion on ES6 support in CEA?

**Comment by joshua1** [comment]
@halfzebra i will get on it in a bit and let you know

**Comment by jackfranklin** [comment]
Sounds reasonable although I know a lot of people would probably never need it.

Would it be possible to have create-elm-app use a `~/.babelrc` file if it existed, else fall back on the defaults?

If that's too complicated though, which it might be, then I don't see the harm in configuring ES2015. I would say that no other presets warrant inclusion by default though. At that point people should eject.

**Comment by lrosa007** [comment]
This is probably a good idea. Sometimes people need to write port related things for elm and it would be nice to have the fancier javascript features for that.

**Comment by gyzerok** [comment]
Hi everyone!

Having ES2015 is indeed a valuable thing. Let's focus a bit on what are those features from ES2015 people would like to have? How wide is their support in browsers right now? Please, come up with more questions if you have.

It's super easy to add babel to the project and let's make sure subject addition brings real value :)

**Comment by lrosa007** [comment]
I was of the impression that one could simply drop in some babel configs without having to worry about which browser supports what. Is this not that case?

**Comment by joshua1** [comment]
@halfzebra i have added ES6 support in a feature branch. trying to submit a PR but have permission issues. Is there something am missing in that regard?

**Comment by lrosa007** [comment]
@joshua1 Did you fork the repo or clone directly?

**Comment by halfzebra** [comment]
Thanks to @joshua1 @jackfranklin @gyzerok @lrosa007 

This feature live 🎉  🙌
