### ISSUE TITLE
Move index.html/js into public folder

### ISSUE THREAD

**Issue by lrosa007** [halfzebra/create-elm-app#123]
Create React App has always been doing this. Is there any reason you decided to put those in the `src` folder? If not, I suggest moving those to a `YOUR_APP/public` folder. This way the `src` folder can stay pure elm. Perhaps I'm missing something and if so let me know. Thanks. I'll gladly PR the adjustments

**Comment by halfzebra** [comment]
@lrosa007 Makes sense!

PR would be very welcome :slightly_smiling_face:

**Comment by lrosa007** [comment]
cool no problem

**Comment by halfzebra** [comment]
The latest release introduces the `public/` folder for static assets, thanks for the issue and the PR!

I'm closing this one in favor of #135
