### ISSUE TITLE
Help with fonts

### ISSUE THREAD

**Issue by cgarciae** [halfzebra/create-elm-app#129]
Hi, I am new to most of front-end development. Your webpack configurations is building all fonts to
```
static/media/**
```
This is giving me errors on deployment. I'd like fonts to build to
```
fonts/roboto/**
fonts/material-icons/**
# etc
```
Any idea how to do this given how `elm-app-create` is structured?

**Comment by halfzebra** [comment]
The latest release introduces `public/` folder, which can be used to serve fonts. 🎉 

Please give it a try!

I'm closing this issue, but please feel free to reopen it if you feel like it does not fix the problem for you!
