### ISSUE TITLE
Obsolete source directory in generated elm-package

### ISSUE THREAD

**Issue by stil4m** [halfzebra/create-elm-app#140]
The `elm-package.json` that is generated (using version `0.8.6`) has the following source directories:

```
...
    "source-directories": [
        ".",
        "src/"
    ],
...
```

I believe the user is stimulated to put the files in `src` while `App.elm` is located there. `"."` currently has no meaning in the generated package. Should this be removed?

**Comment by halfzebra** [comment]
Hello @stil4m!

Thanks for the contribution, would you like to send a PR for that?

**Comment by stil4m** [comment]
Sure :).
