### ISSUE TITLE
Section "Adding a stylesheet" is missing from documentation

### ISSUE THREAD

**Issue by groma84** [halfzebra/create-elm-app#145]
In various parts of the [documentation ](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md) there are links to the section [adding a stylesheet](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#adding-a-stylesheet) but that part of the documentation does not exist.

As I'm just starting out with Elm and create-elm-app I sadly don't know enough yet to make a pull request with the section added.

**Comment by halfzebra** [comment]
@groma84 thanks for the contribution, this have been fixed!
