### ISSUE TITLE
Windows 8.1, latest version: Elm debugger is disabled by default

### ISSUE THREAD

**Issue by groma84** [halfzebra/create-elm-app#153]
I'm not sure if this is the intended behaviour or not - but judging from the release changelog I expected the Elm debugger to still be active by default.
At least in Windows 8.1 this is not the case: If the environment variable is not present at all the Elm debugger is disabled.

**Comment by halfzebra** [comment]
@groma84 Thanks for the contribution!

This is clearly a mistake, the fix is coming asap.
