### ISSUE TITLE
relative paths in prod build

### ISSUE THREAD

**Issue by damukles** [halfzebra/create-elm-app#154]
**Background**
When I make a prod build `elm-app build` the index.html contains absolute paths to the js and the css. This prevented me from deploying the app under a subfolder like https://example.com/app/.
After I changed the paths in the index.html to relative paths, the app worked.

**Suggestion**
I suggest to change all absolute paths to relative paths in production build to support deploying to subfolders.

**Comment by joakin** [comment]
You can use `PUBLIC_PATH` like so:

https://github.com/joakin/water-automata/blob/master/package.json#L3

😃

**Comment by damukles** [comment]
I see, thanks.

**Comment by joakin** [comment]
And of course I mistyped it. The actual variable is `PUBLIC_URL`.

It is kind of mentioned here https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#using-the-public-folder but not explicitly that you can set it before calling `elm-app`.
