### ISSUE TITLE
Improve the documentation on Environment variables

### ISSUE THREAD

**Issue by DanielBlanco** [halfzebra/create-elm-app#161]
I had to read the code in `/config/env.js` to know that only `NODE_ENV` and `ELM_APP_*` environment variables are fetched from `.env` file.

Please add a section on how to setup and use `.env` in your [User Guide](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md), hopefully with some samples on how to pass the data to ELM like:

```JavaScript
Main.embed(document.getElementById('root'), {
  test: process.env.ELM_APP_TEST
});
...
```

**Comment by halfzebra** [comment]
@DanielBlanco thanks for pointing that out! It was a recent addition to Create Elm App, which was made for security reasons.

Would you like to work on PR?

**Comment by ca057** [comment]
I would like to help out here with a PR - do you have a specific place in mind where to place this documentation? Otherwise I would put it in the User Guide between "Adding Images and Fonts" and
"Using the public Folder".

**Comment by halfzebra** [comment]
@ca057 awesome!

A PR would be very welcome!

I think it would make sense to have these docs right after [Using the `public` Folder](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#using-the-public-folder) section, but the order is not that important.

Please make sure to add an anchor for navigation 🙂
