### ISSUE TITLE
Uglification failing on ES6 Syntax

### ISSUE THREAD

**Issue by CallumJHays** [halfzebra/create-elm-app#162]
When I run: `npm run build` I get the output:
![image](https://user-images.githubusercontent.com/13251689/29246487-30fc0066-803f-11e7-8678-504d59673fc7.png)
This appears to be a result of UglifyJS not being capable of parsing ES6 Syntax - which, if my understanding is correct, should not be present in the code at that point of the build stage - due to the `babel-presets` module.rules for the webpack config in `config/webpack.config.prod.js`.

I'm a complete noob when it comes to webpack - so this is more a cry for help rather than an actual issue

Thanks!

**Comment by fobos** [comment]
Hi @CallumJHays.

To build an application you should use `elm-app build` command&.
Could you explain me reason why do you use `npm tun build` instead?

**Comment by CallumJHays** [comment]
Hi @fobos, thanks for the reply!

I have ejected the dependencies of the app on `elm-app` into the folder using `elm-app eject`.

Although I tried building using `elm-app build` and I get the same UglifyJS error, without the npm errors.

**Comment by halfzebra** [comment]
@CallumJHays Thanks for reporting this, have you managed to figure out what code is causing the error?

Create Elm App comes with Babel setup, which transpiles ES6 code in `src/`, are you importing something from the outside?

I would be super helpful if you could share some kind of example so we could reproduce this.

**Comment by CallumJHays** [comment]
HI @halfzebra, thanks for your advice!

After further testing, I think I've narrowed down the issue to certain npm imports within JS files causing the issue. These npm modules being imported use es6 syntax as shown in the picture below (the line of the file which caused the UglifyJS plugin to panic). (line 4664, at the default parameter)

Eg:
![image](https://user-images.githubusercontent.com/13251689/29250008-119b5516-807e-11e7-9d7b-5c588421ee74.png)

The package that caused this failure was vis-js, with the import statement:

```js
import buildCrash from 'vis/index-network'
```

I double-checked this by starting a new `create-elm-app` project and removing every file in `src/` **but** `index.js`, with the above line as the only command. This causes the production build to fail.

Is it possible to import packages from the `node_modules` folder that contain es6 syntax and have it all compile properly?

**Comment by halfzebra** [comment]
@CallumJHays in short, you should use pre-compiled distribution of the library and import it from [`vis/dist`](https://github.com/almende/vis/tree/master/dist)

It looks like [this](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) part of Create React App applies to your use-case.

We do not transpile code in `node_modules/`, because it's impossible to predict, which Babel configuration is required for different modules.

If you need future help with that, I would recommend publishing a little example if that makes sense 🙂

**Comment by CallumJHays** [comment]
Thanks @halfzebra!

Using `vis/dist` as you suggested did the trick! I will be sure to check that I'm only importing commonJS modules from now on :)

**Comment by halfzebra** [comment]
@CallumJHays happy to help!
