### ISSUE TITLE
Generated index.html's links break when it's not directly under the root.

### ISSUE THREAD

**Issue by ryuheechul** [halfzebra/create-elm-app#163]
This is the file that generated by `elm-app build`
https://github.com/ryuheechul/save-the-date/blob/19d1b3499403bc5853fe61da848da2eb99148e0f/index.html
except I had to change things below to make it work when it's not directly under the root, too.

```
href="/favicon.ico" -> href="favicon.ico"
src="/static/js/main.d00a9455.js" -> src="static/js/main.d00a9455.js"
href="/static/css/main.64e4dd2f.css" -> href="static/css/main.64e4dd2f.css"
```

And I serve that page currently via Github Pages, and it's url is like `username.github.io/project` which is not root url. so I can guess probably many folks could do the same since Github Pages is popular.
So, I think these links should be relative not absolute to be more flexible.

**Comment by halfzebra** [comment]
@ryuheechul hello!

I'm afraid you're missing some configuration there, please check out the [User Guide: Deployment - GitHub Pages.](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#github-pages)

It looks like you're missing the `"homepage"` property.

Please let me know if that helps.

**Comment by ryuheechul** [comment]
Hi @halfzebra!

Thanks for your answer and it solved the issue! 👍 
I should have read [that readme](User Guide: Deployment - GitHub Pages.) more carefully.
Also, thanks for your work for this awesome create-elm-app!

**Comment by halfzebra** [comment]
@ryuheechul happy to help! Thanks for reaching us out 👍

**Comment by ryuheechul** [comment]
@halfzebra I just found another issue relate to this. Which it still breaks the references when you use custom domains for GitHub page because custom domain treat assets as the root level.

What do you think can be a good way to resolve this issue?

**Comment by halfzebra** [comment]
@ryuheechul hello again!

Could you please provide an example of current and expected output for paths?

**Comment by ryuheechul** [comment]
@halfzebra hello again!

For example, [this](https://github.com/ryuheechul/save-the-date/tree/gh-pages) is a website that I made with create-elm-app. (thanks to you guys!)

Although it works with a URL like `https://ryuheechul.github.io/save-the-date`, when you serve it locally using something like [serve](https://www.npmjs.com/package/serve) or whatever the web server, it doesn't work.

Because the output paths are absolute so this only work when the url pattern becomes `[example.com]/save-the-date`. Since GitHub pages also can be served with your custom domain (and it will be most likely root level url) as well as `github.io/project` at the same time, I see this as a not flexible built.

So I think output paths should be relative like [this](https://github.com/halfzebra/create-elm-app/issues/163#issue-251803853)

Let me know about your thoughts!

**Comment by halfzebra** [comment]
Took me a while to figure out the issue.

The distribution has to be built with a different `"homepage"` if you want to serve it locally.

I'm closing this due to the age of the issue, sorry I couldn't address this back then.

**Comment by ryuheechul** [comment]
>Took me a while to figure out the issue. ...

@halfzebra no problem. Thanks for coming back to handle the issue anyway 👍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
