### ISSUE TITLE
CSS modules?

### ISSUE THREAD

**Issue by hipertracker** [halfzebra/create-elm-app#176]
How to use CSS modules in create-elm-app? E.g. I'd like to import in JS not css but css module.

**Comment by halfzebra** [comment]
Hello @hipertracker! Thanks for the question.

At the moment [ejecting](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#elm-app-eject) is your only option.

CSS modules are most likely will be in Create React App [create-react-app/issues/2278](https://github.com/facebookincubator/create-react-app/issues/2278) and we will consider adding this feature if there's enough interest.

@fobos @gyzerok @jackfranklin thoughts?

**Comment by gyzerok** [comment]
@hipertracker how much JavaScript/Elm code do you have in your app? How is it structured? What is your JavaScript code doing?

@halfzebra personally I don't see much use of CSS Modules in Elm application. You probably won't have too much JS code and even if you will it shouldn't be about view. So I'd consider amount of potential users of this feature pretty low. At the same time it will increase maintenance cost.

**Comment by halfzebra** [comment]
@gyzerok thanks for the reply! 👍 

This feature is fairly simple to implement, but it surely complicates the post-eject life.

We had a similar conversation about [elm-css](https://github.com/halfzebra/create-elm-app/pull/137), I suppose there are not enough use-cases for including CSS Modules into the default config so far.

**Comment by hipertracker** [comment]
@halfzebra my project uses React and [Cerebral](https://cerebraljs.com/) with few [embed Elm components](https://gist.github.com/hipertracker/1423ac96662d49e432f20472478499b3). For the moment I use https://github.com/kitze/custom-react-scripts instead of original `create-react-app`. I'd like to use `create-elm-app` instead but I need CSS modules.

**Comment by hipertracker** [comment]
I guess, there is no need to eject to add CSS modules. It can be all customized through the fork of  `react-scripts`. At least this works for FB `create-react-app`

**Comment by jackfranklin** [comment]
I think CSS modules in Elm is definitely something that is a good option for ejecting - especially as there isn't as much use of it (as I'm aware) in the Elm community as there is in the JS one. I'd say leave this issue as one where others can voice if this would be useful or not.

**Comment by hipertracker** [comment]
I don't like `eject` because this is a one way ticket. Once you do it you are on your own. You can't get benefits from the later `create-elm-app` upgrades.

**Comment by gyzerok** [comment]
@hipertracker you can create a fork and add specific things you need. Then you can merge upstream once it have some changes.

**Comment by hipertracker** [comment]
OK, if nobody is interested in the hybrid approach here.... I have just created the fork and added CSS modules and React support. I described how to use it at the end of README file. https://github.com/hipertracker/create-elm-app. Currently I have React and CSS modules. (Later I plan to add SASS, LESS, Stylus modules as well, like in kitze/custom-react-scripts)

**Comment by halfzebra** [comment]
I'm closing this, #311 allows having the configuration for modules if necessary.

Please feel free to reopen if anyone is interested in discussing the option of having the support for CSS Modules.
