### ISSUE TITLE
A command to install all dependencies

### ISSUE THREAD

**Issue by jackfranklin** [halfzebra/create-elm-app#182]
I'd like to be able to run `elm app install` and have it:

- `elm-package install --yes`
- `elm-test --add-dependencies tests/elm-package.json`
- `cd tests && elm-package install --yes`

So that it's nice and easy to keep my dependencies up to date and for new users to install everything too.

What do you think to adding that as a script? I'm happy to do the PR :)

**Comment by fobos** [comment]
Sounds interesting. 👍

**Comment by halfzebra** [comment]
@jackfranklin thanks for the idea, I'm pretty sure will be a very nice addition to the existing functionality.

I'm not sure about the `cd tests && elm-package install --yes` though, those dependencies will be installed on `elm-app test` anyway.

It shouldn't do anything when `tests/` folder is not present.

PR would be very welcome!

**Comment by jackfranklin** [comment]
Ah I didn't realise that elm-test does that!

I was thinking about this today and think that instead we should have:

- `elm app install` => `elm package install --yes`
- on `elm app test` we should first run `elm-test --add-dependencies tests/elm-package.json` before running the tests

What do you think?

**Comment by halfzebra** [comment]
@jackfranklin I like both suggestions. :+1: 

Just double-checked, `elm-test` installs the packages if they are missing in `tests/` or on the root level(or both)

**Comment by jackfranklin** [comment]
@halfzebra I'll get a PR in sometime :)

**Comment by halfzebra** [comment]
I'm afraid this is not relevant as of `0.19`

Closing for now, please feel free to reopen if there's something that can be addressed.
