### ISSUE TITLE
Time stepping debugger with `elm-app build`

### ISSUE THREAD

**Issue by tzemanovic** [halfzebra/create-elm-app#187]
Hi Ed,

I'd like to build an output with `elm-app build` that still has Time stepping debugger for my staging environment. This doesn't seem possible atm, but I think it would be as simple as switching on the `debug` flag in 'elm-webpack-loader' for the `prod` build config, just like in the `dev` config: https://github.com/halfzebra/create-elm-app/blob/db4986d10e1550b9ab95fa48e7a12e2e213807f2/config/webpack.config.dev.js#L125

I can put together a PR for this, if you're happy to get this in.

Many Thanks,
Tomas

**Comment by halfzebra** [comment]
@tzemanovic good suggestion! 👍 

I feel like it would make sense to disable the debugger in the build by default and let people enable it by using an environment variable.

The development mode enables it by default and lets you disable it of it is causing issues while working with large collections.

**Comment by tzemanovic** [comment]
Agreed, cheers!

**Comment by halfzebra** [comment]
@tzemanovic PRs are welcome, if you're up for it :slightly_smiling_face:

**Comment by halfzebra** [comment]
Closed by #190
