### ISSUE TITLE
Improve Webpack configuration docs

### ISSUE THREAD

**Issue by halfzebra** [halfzebra/create-elm-app#19]
As a user, who want's to `eject`, I would like to have more information in `webpack.config` files

Add comments, describing configuration code.

**Comment by pzingg** [comment]
Also (as a webpack newbie), I would like to have some information on:

* where to put Javascript code for Elm ports (I figured this out--you create a script tag in index.js)
* how to add static media files to your project (I could not figure this out; no matter where I put a .jpg source file, I didn't see it being loaded into dist or static/media or whereever it might supposed to be going).

I have Elm code that inserts a CSS ```background: url('path/to/a.jpg')``` style. Where do I add my "a.jpg" file and what is the path that it will end up as? Or do I have to "require" the "a.jpg" file somewhere?

**Comment by halfzebra** [comment]
@pzingg Thank you for your contribution! I will look in to this for the next release 👍

**Comment by halfzebra** [comment]
Closing this for now.
