### ISSUE TITLE
Babel Polyfill?

### ISSUE THREAD

**Issue by screendriver** [halfzebra/create-elm-app#198]
Would it be possible to include the [Babel Polyfill](https://babeljs.io/docs/usage/polyfill/) by default so we can use things like `Promise`, `Map`, `async / await` and so on in my JavaScript / Elm `port`? With that we don't have to include that by ourself.

**Comment by halfzebra** [comment]
@screendriver this is a good idea 👍 

Would you like to work on a PR?

**Comment by screendriver** [comment]
I would do that but at the moment I'm not quite sure how to because the Babel polyfill is a real **huge** package and should not always be included. For smaller projects that don't need it it would increase the final bundle size heavily. Maybe we should include the [runtime transform](https://babeljs.io/docs/plugins/transform-runtime/) plugin instead? 🤔

**Comment by halfzebra** [comment]
@screendriver I'm afraid I didn't think it through 🙂 

Including the entire `babel-polyfill` is not an option, but polyfilling `Promise` and `async / await` makes sense. I think Create React App has a pretty good [example](https://github.com/facebookincubator/create-react-app/blob/master/packages/babel-preset-react-app/index.js) of implementing this.

Runtime transform is exactly the thing we should use!

**Comment by screendriver** [comment]
All right. I will make a pull request in the next couple of days ☺️
