### ISSUE TITLE
Http headers not working with build command, but work fine using start

### ISSUE THREAD

**Issue by danbroooks** [halfzebra/create-elm-app#203]
I've created an example repository to demonstrate this issue.

If you clone [this repository](https://github.com/danbroooks/create-elm-app-http-headers) and then run `elm-app start`, clicking the button on the page will trigger the http request with the relevant headers like so:

![screen shot 2017-11-10 at 09 21 49](https://user-images.githubusercontent.com/2951404/32651712-c9e6ee6c-c5f9-11e7-894d-7060b8a56ab4.png)

But then building the app with `elm-app build`, and serving the files with something like `touch ./build/api && http-server ./build`, I get:

![screen shot 2017-11-10 at 09 33 59](https://user-images.githubusercontent.com/2951404/32651875-4f934308-c5fa-11e7-80d7-10bcf8cdeac7.png)

Note the lack of `Authorization Bearer token` in the request headers.

**Comment by danbroooks** [comment]
Funnily enough I have just updated to `create-elm-app@1.9.1` and I don't seem to be getting the same behavior.

**Comment by halfzebra** [comment]
@danbroooks thanks for reporting this issue.

It's only a guess, but there's a chance that [dead code elimination](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#dead-code-elimination) was causing this issue.

Please let us know if you will experience this again.

**Comment by danbroooks** [comment]
Great stuff, fixed this issue on my existing app by copying the contents of `webpack.config.prod.js` into my app (which effectively [adds the flag to disable dead code elimination](https://github.com/halfzebra/create-elm-app/blob/master/config/webpack.config.prod.js#L42)).
