### ISSUE TITLE
Update npm dependencies: react-error-overlay

### ISSUE THREAD

**Issue by andys8** [halfzebra/create-elm-app#207]
If you're going to update to.
```sh
    "react-dev-utils": "4.2.1",
    "react-error-overlay": "3.0.0",
```

There will be a change (because of internal migration) in `webpackDevServer.config.js`

## before
`const errorOverlayMiddleware = require('react-error-overlay/middleware');`

## fix
`const errorOverlayMiddleware = require('react-dev-utils/errorOverlayMiddleware');`

I wanted to add this information, because it took me some time to update the dependencies and this is one of the breaking changes I had.

**Comment by halfzebra** [comment]
@andys8 thanks for the issue, it should be ubdated now :slightly_smiling_face:
