### ISSUE TITLE
Native module not including node packages

### ISSUE THREAD

**Issue by Libbum** [halfzebra/create-elm-app#215]
### Is this a bug report?

No. At least it's most likely just my setup.

### Environment

1. `node -v`: v9.3.0
2. `npm -v`: 5.6.0
3. `yarn --version` (if you use Yarn): nope
4. `npm ls create-elm-app -g` (if you haven’t ejected): 
/usr/lib
└── create-elm-app@1.9.1

1. Operating system: Arch Linux
2. Browser and version (if relevant): Chromium 63.0.3239.108

### Problem

I'm moving an active project over from using Brunch as a build system and am having issues getting a native module compiled that requires node packages inside it.

From the readme, I've installed the packages, and `package.json` has the following section:

```json
"devDependencies": {
    "markdown-it": "^8.4.0",
    "markdown-it-katex": "^2.0.3"
  }
```
 
Then, somewhere in `src/Native/Markdown.js` I have the lines:

```javascript
const md = require('markdown-it')(options.preset, options),
         mk = require('markdown-it-katex');
md.use(mk);
```

which was working fine with my brunch configuration, but now I seem to be getting reference errors, and the two packages are not being pulled in by the build scripts. Is there something specific I need to configure for these packages to be included at this point?

**Comment by halfzebra** [comment]
@Libbum thanks for reporting this issue!

Sorry, it took me a while to get back to you.

We don't support the native modules in Create Elm App, but it's surely possible to eject and modify the config slightly to get the desired behavior.

Run `elm-app eject`

Locate `config/webpack.config.dev.js` and `config/webpack.config.prod.js` and do the following changes:

Make Webpack look Elm code for imports:

```diff
  module: {
-    noParse: /\.elm$/,

    rules: [
```

Process compiled by Elm Compiler JavaScript with Babel to transpile ES6 from your native modules:

```diff

      {
        test: /\.elm$/,
        exclude: [/elm-stuff/, /node_modules/],
        use: [
+          {
+            loader: require.resolve('babel-loader'),
+            query: {
+              // Latest stable ECMAScript features
+              presets: [
+                [
+                  require.resolve('babel-preset-env'),
+                  {
+                    targets: {
+                      // React parses on ie 9, so we should too
+                      ie: 9,
+                      // We currently minify with uglify
+                      // Remove after https://github.com/mishoo/UglifyJS2/issues/448
+                      uglify: true
+                    },
+                    // Disable polyfill transforms
+                    useBuiltIns: false,
+                    // Do not transform modules to CJS
+                    modules: false
+                  }
+                ]
+              ],
+              plugins: [
+                [
+                  require.resolve('babel-plugin-transform-runtime'),
+                  {
+                    helpers: false,
+                    polyfill: false,
+                    regenerator: true
+                  }
+                ]
+              ]
+            }
+          },

```

I hope this helps.

If this issue gets more attention, we might include some basic support for native modules.

**Comment by Libbum** [comment]
Excellent, thanks for the details. I'm on holiday myself, so no worries about the delay. Will be a few more days before I can test this out.

**Comment by halfzebra** [comment]
@Libbum have a nice holiday! Let me know if this works 🙂 

I'm closing this issue, but please feel free to reopen it if this needs more attention.

**Comment by Libbum** [comment]
Can confirm this works. Thanks again.
