### ISSUE TITLE
Development in IE11 impossible (Blank page)

### ISSUE THREAD

**Issue by EvertVerboven** [halfzebra/create-elm-app#217]
### Is this a bug report?

Yes

### Environment

1. `node -v`: v8.4.0
2. `npm -v`: 5.6.0
3. `yarn --version` (if you use Yarn): 0.27.5
4. `npm ls create-elm-app -g` (if you haven’t ejected): 1.10.1

Then, specify:

1. Operating system: MacOS Sierra 10.12.6 (Development) / Win7 Virtual Machine
2. Browser and version (if relevant): IE11 11.0.9600 In virtual machine

### Steps to Reproduce

When starting the development server, and visiting 10.0.2.2:3000 in a windows virtual machine IE11 browser (maps to localhost:3000) on the actual machine a blank page shows up.

In the console the error 

(Write your steps here:)

1. `$ create-elm-app foo`
2. `$ cd foo`
3. `$ elm-app start`
4. visit `10.0.2.2:3000` in IE11 on windows virtual machine
5. see blank page, inspect, reload to see error

### Expected Behavior

I woud expect to see the create-elm-app initial page `Your elm app is working`

### Actual Behavior

A blank page appears with an error in the console

![screen shot 2017-12-22 at 13 36 06](https://user-images.githubusercontent.com/22809599/34298257-33492228-e71d-11e7-97a2-7011493ed205.png)
![screen shot 2017-12-22 at 13 36 17](https://user-images.githubusercontent.com/22809599/34298258-335c30de-e71d-11e7-9285-923f20fb9b9f.png)

### Reproducible Demo

I did not include a demo since the issue appears immediately after creating a new elm-app.

**Comment by kspeakman** [comment]
I have this same problem. It is because the dev build does not convert JS arrow functions in the `color-convert` modules into classic functions. IE11 cannot use ES6 arrow functions. Not sure if color-convert is getting injected after the normal build process or what.
