### ISSUE TITLE
elm-hot-loader no longer maintained

### ISSUE THREAD

**Issue by xtian** [halfzebra/create-elm-app#229]
The elm-hot-loader repo has been archived and marked as no longer maintained:

https://github.com/fluxxu/elm-hot-loader/commit/79c94c0af84d79821395e1dd019257375cf8f7db

I'm not aware of any outstanding issues with this module, but it may make sense to explore other options for providing this functionality.

**Comment by halfzebra** [comment]
@xtian good point, I don't see any alternatives at the moment.

We have a meetup tomorrow, so I'll try to figure out if [elm-community](https://github.com/elm-community) will be taking over.

Otherwise maintaining a fork is always an option. 🤔

**Comment by halfzebra** [comment]
So far I've learned that no more work on HMR for Webpack will be done before `0.19.0` is out.

The API will change on the Elm side, so we'll see what could be done after the release.

**Comment by halfzebra** [comment]
Probably related https://github.com/klazuka/elm-hot

**Comment by klazuka** [comment]
Yep, I've forked fluxxu's code and got it working with Elm 0.19 and a forked version of elm-webpack-loader that supports 0.19. It's not yet ready for public consumption, but getting closer.

**Comment by halfzebra** [comment]
That's very good news, please let me know if I can help in some way 👍

**Comment by klazuka** [comment]
@halfzebra I published the HMR webpack loader as [a separate package](https://github.com/klazuka/elm-hot-webpack-loader) (because I want to keep the core independent of Webpack). It's ready for use/evaluation with the caveat that 0.19 support for elm-webpack-loader has not yet shipped.
