### ISSUE TITLE
With new install, elm-app start does not work

### ISSUE THREAD

**Issue by greglearns** [halfzebra/create-elm-app#239]
### Is this a bug report?

Yes

### Environment

greg test_ui$ node -v                                                                                                                                                                        v9.7.1
greg test_ui$ npm -v                                                                                                                                                                         5.6.0
greg test_ui$ npm ls create-elm-app -g                                                                                                                                                       /usr/local/lib
└── create-elm-app@1.10.3

Then, specify:

1. Operating system: MacOSX Sierra 10.12.6
2. Browser and version (if relevant): NA

### Steps to Reproduce

brew install npm
npm install create-elm-app -g
create-elm-app test_ui
cd test_ui
elm-app start
Could not find an open port at Gs-MacBook-Pro.local.
Network error message: getaddrinfo ENOTFOUND Gs-MacBook-Pro.local

### Expected Behavior

The tool should have enabled elm-app start to work. Instead, it errored out.

### Actual Behavior

Instead, got an error (see error above in the "steps to reproduce" section)

### Reproducible Demo

https://github.com/greglearns/test_ui

See "how to reproduce" section above for steps used to create the github repo and the error.

**Comment by halfzebra** [comment]
Hello @greglearns, sorry it took me a while to write a reply.

There's a problem with https://www.npmjs.com/package/detect-port-alt package, which is a fork of another package(which has this bug fixed)

I have reported the bug to the maintainers of Create React App, that's all I can do at the moment 🤔

**Comment by greglearns** [comment]
The (temporary) Solution is:

HOST=localhost elm-app start  # pick port 3000, or, if that is used, then a random port
HOST=localhost PORT=5000 elm-app start  # assign a port
HOST=localhost PORT=5000 npm run start  # if you have ejected

Everything works great.

Thank you @halfzebra; it has been a pleasure working with create-elm-app.

**Comment by mickeyvip** [comment]
@greglearns, how exactly do you set the port?

**Comment by halfzebra** [comment]
This issue has been addressed in `detect-port-alt`, I'm closing this one.

Please feel free to reopen if necessary!
