### ISSUE TITLE
Instead of "New content is available; please refresh", how override to update content?

### ISSUE THREAD

**Issue by greglearns** [halfzebra/create-elm-app#240]
### Is this a bug report?

No

### Issue

As soon as new content is pulled by the service worker, I'd like to automatically reload that content.  OR, display content in the main Elm app to tell the user to reload. What is the best (elm?) way to do that?

Thank you! Awesome project, by the way.

**Comment by littleStudent** [comment]
Never thought about it until now. I would try the following:
Not sure but i think you need to `eject` to access the serviceworker file.
create a Port for telling your elm app that new content is available. So you can react to that when and however you want. 
In case the SW knows there is new content use the Port.

Not sure if we should change anything for `create-elm-app`?

**Comment by halfzebra** [comment]
Hi @greglearns, thanks for the question!

The `service-worker.js` file is generated by [goldhand/sw-precache-webpack-plugin](https://github.com/goldhand/sw-precache-webpack-plugin), which provides a generic and fairly limited functionality for caching the assets, emitted by Webpack.

I'm afraid that the only way to customize this behavior is to `eject` and take it from there as @littleStudent suggests.

**Comment by greglearns** [comment]
Thank you!

**Comment by halfzebra** [comment]
@greglearns sorry I couldn't suggest anything better :slightly_smiling_face: 

I will be closing this issue.

Please feel free to re-open if you'll find it necessary!
