### ISSUE TITLE
[Question] Any interest in using Webpack v4 ?

### ISSUE THREAD

**Issue by pruett** [halfzebra/create-elm-app#241]
### Is this a bug report?

No

Is there any interest in upgrading to Webpack v4? Are there any known issues with upgrading to v4? If it is of interest, I or someone else can likely provide a hand in upgrading.

**Comment by andys8** [comment]
There is interest and it would be awesome if you help to upgrade the project.

**Comment by halfzebra** [comment]
Hi @pruett, thanks for creating this issue!

There is interest in upgrading, but as far as I know, Webpack 4 [is not yet supported by elm-webpack-loader.](https://github.com/elm-community/elm-webpack-loader/issues/134)

It looks like the fix is on the way, so we will be able to upgrade.

PRs are very welcome!

**Comment by praveenperera** [comment]
I think once [these changes ](https://github.com/facebook/create-react-app/pull/4077/files) are made it should be easier right?

**Comment by pruett** [comment]
good point @praveenperera. but of the react-dev-utils deps that CEA uses, it looks like they are just updating to new `hook` plugin api, which i *think* will only throw a warning but will still compile with v4. the elm-wepback-loader is the biggest obstacle at the moment as mentioned above

**Comment by praveenperera** [comment]
@pruett right and it looks like its actually fixed: https://github.com/elm-community/elm-webpack-loader/pull/136. Just waiting for the new version to published

**Comment by optikfluffel** [comment]
[elm-community/elm-webpack-loader 4.5.0](https://github.com/elm-community/elm-webpack-loader/releases/tag/4.5.0) just got released ^^

**Comment by halfzebra** [comment]
Closed in #272
