### ISSUE TITLE
Question: elm-app for multiple targets

### ISSUE THREAD

**Issue by geekyme** [halfzebra/create-elm-app#246]
Use case: building a browser extension with Elm.

A browser extension typically contains a popup, a background script, and a content script, which are all sandboxed and require separate scripts.

How do i use elm-app to emit the 3 different scripts?

**Comment by geekyme** [comment]
Yup @halfzebra I ejected the configuration and modified for 3 targets. So far running "npm run build" helps me to output the 3 scripts correctly. 

But I would love to have the hot reloads a short I write the 3 parts of the application. Would you happen to know how to do that?

**Comment by geekyme** [comment]
ie. Making type errors on popup.elm, content.elm, background.elm will show me errors immediately vs running the full build to see it.

**Comment by halfzebra** [comment]
I'm not sure if #311 covers this entirely, but it sure helps to avoid ejection.

Please feel free to reopen this if necessary! 🙂
