### ISSUE TITLE
elm-app test --add-dependencies elm-package.json does add already installed dependencies

### ISSUE THREAD

**Issue by 3nigm4** [halfzebra/create-elm-app#247]
### Is this a bug report?

yes

### Environment

1. `node -v`: v9.11.1
2. `npm -v`: 5.8.0
3. `yarn --version` (if you use Yarn): no
4. `npm ls create-elm-app -g` (if you haven’t ejected): 
/home/bruno/.npm-packages/lib
└── create-elm-app@1.10.3 

Then, specify:

1. Operating system: Arch Linux
2. Browser and version (if relevant): Firefox 59

### Steps to Reproduce

1. create-elm-app fooo
2. cd fooo
3. elm-app install elm-lang/navigation
4. added to Main.elm : import Navigation
4. in tests/Tests.elm added:
             import Main as SUT exposing (functionToTest)
5. from .../fooo : elm-app test --add-dependencies elm-package.json
6. elm-app test
... with output:
```
I cannot find module 'Navigation'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
Compilation failed while attempting to build /home/bruno/CODE/ELM/learning/fooo/tests/Tests.elm
```
7. cat ./tests/elm-package.json
reveals navigation was not added to tests package json

### Expected Behavior

Expected elm-lang/navigation to be added to package json in tests directory

### Actual Behavior

was not added

### Reproducible Demo

please follow my steps above

**Comment by halfzebra** [comment]
@3nigm4 thanks for reporting this issue!

The documentation is misleading, the second argument for `elm-app test` is the path to the `elm-package.json` you want to update!

The correct way would be running the following:

```sh
# While in the root of your project
elm-app test --add-dependencies tests/elm-package.json
```

I have updated the docs in #250 so I'm closing this issue 🙂
