### ISSUE TITLE
Document proxy setting can be object

### ISSUE THREAD

**Issue by jhillyerd** [halfzebra/create-elm-app#251]
### Is this a bug report?

No.

### Environment

1. `node -v`: v8.11.1
2. `npm -v`: 5.8.0
3. `yarn --version` (if you use Yarn):
4. `npm ls create-elm-app -g` (if you haven’t ejected): create-elm-app@1.10.3

### Documentation request

It would be helpful if the template README.md included a note that the `elm-package.json:proxy` setting can be either a string, or an object.  As an example, I was able to get websocket proxying working with my project by using the following:

```
...
    "exposed-modules": [],
    "proxy": {
      "/api": {
        "target": "http://localhost:9000",
        "ws": true
      },
      "/debug": {
        "target": "http://localhost:9000"
      }
    },
    "dependencies": {
...
```

It may make sense to link to create-react-app docs or https://github.com/chimurai/http-proxy-middleware

**Comment by halfzebra** [comment]
@jhillyerd good point! :+1: 

Would you be interested in doing a PR?

**Comment by jhillyerd** [comment]
I'm not opposed to that, was waiting to know what the plans were for #160 just to make sure the docs to not become incorrect.

**Comment by kornicameister** [comment]
@halfzebra @jhillyerd any news here? I am not struggling with new approach introduced by latest `2.2.3` version of `create-elm-app` and have no idea how to set proxy similar to that one:

```
proxy: {
  '/api': {
   target: 'https://backend.com',
   secure: False,
  }
}
```

is it still doable?

**Comment by kornicameister** [comment]
One thing more. https://github.com/halfzebra/create-elm-app/blob/master/scripts/start.js#L165 calls `configureWebpack` method that ought to write down the my mods, but the proxy modification is being done couple lines below. Doesn't it mean that even if I do it correctly in override, I will still get my mods overridden?

**Comment by halfzebra** [comment]
Hi @kornicameister! I think what you are looking for is the undocumented feature of proxy setting.

Try creating `elmapp.config.js` with the following configuration:

```js
module.exports = {
  proxy: {
    '/api': {
      target: 'https://backend.com',
      secure: False,
    }
  }
}
```

Please let us know if this helps!

**Comment by kornicameister** [comment]
I think I did but then react-dev-utils were complaining about proxy being an object and not a string. So I tried there sugestion from https://facebook.github.io/create-react-app/docs/proxying-api-requests-in-development to configure it manually and it was not working as well.

**Comment by jhillyerd** [comment]
Ditto:

```
> cat elmapp.config.js 
module.exports = {
  proxy: {
    '/api': {
      'target': 'http://localhost:9000',
      'ws': true
    },
    '/debug': {
      'target': 'http://localhost:9000'
    },
    '/serve': {
      'target': 'http://localhost:9000'
    }
  }
}
```

```
> elm-app start                                                                                                                                            
When specified, "proxy" in package.json must be a string.                                                                                                   
Instead, the type of "proxy" was "object".                                                                                                                  
Either remove "proxy" from package.json, or make it a string.
```

**Comment by jhillyerd** [comment]
Tried using the `module.exports = function(app) { // code }` (in elmapp.config.js), but it doesn't work, pretty sure it never gets called.

Also tried making webpack.config.js from https://webpack.js.org/configuration/dev-server/#devserver-proxy with success.

**Comment by kornicameister** [comment]
Reported once again in #326. @halfzebra is there anything you can recommend to get the old proxy working. I'd really love to upgrade.

**Comment by jhillyerd** [comment]
Sadly, I never found a work around.  I had to drop create-elm-app.

**Comment by halfzebra** [comment]
Hello @kornicameister and @jhillyerd!

I have finally looked into this and there's a[ potential fix ](https://github.com/halfzebra/create-elm-app/issues/326) for the issues you are experiencing.

Please check it out if you are still interested in using Create Elm App!

**Comment by jhillyerd** [comment]
That's exciting news.  Definitely makes it easier to recommend create-elm-app in the future.

**Comment by halfzebra** [comment]
Closing this issue, with `create-elm-app@3` proxy can no longer be configured with an object.

Please read on advanced proxy usage [here](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#configuring-the-proxy-manually)
