### ISSUE TITLE
Failed to construct 'HTMLElement'

### ISSUE THREAD

**Issue by nqthqn** [halfzebra/create-elm-app#252]
### Is this a bug report?

Sort of. I think I need to use a more recent version of babel. I want to do this without ejecting. Can we update the deps for this project? If so - can I upgrade my project since I already made it with `create-elm-app` ? Better yet — built in support for custom elements with some boilerplate code.

### Environment

1. `node -v`: v9.3.0
2. `npm -v`: 5.6.0
3. `npm ls create-elm-app -g` : 

```
/usr/local/lib
└── create-elm-app@1.10.4
```

1. Operating system: Mac OSX (10.13.4 (17E199))
2. Browser and version (if relevant): Google Chrome, Version 65.0.3325.181 (Official Build) (64-bit)

### Steps to Reproduce

1. Create a Custom Element
2. Import it into index.js
3. Add shim and polyfill
4. Use the element in Elm

### Expected Behavior

I would see a `pop-menu` custom html element in the DOM

### Actual Behavior

```
TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

### Reproducible Demo

Coming soon.

**Comment by krksgbr** [comment]
I also came across this issue when trying to use a custom web-component from elm code.
I managed to get a setup working which seems to solve the issue, though it also requires ejecting.

[link to an example project repo](https://github.com/krksgbr/create-elm-app-webcomponents-setup)
[link to the commit containing all the necessary modifications](https://github.com/krksgbr/create-elm-app-webcomponents-setup/commit/9e805932ece06a795071b4897d7366ec87ce6057)

I hope this helps.

**Comment by nqthqn** [comment]
I ended up ejecting.

I'm thinking of switching to a simpler build procedure

**Comment by opsb** [comment]
The following is remarkably painfree and doesn't require ejecting

```
$ npm install @webcomponents/custom-elements --save
```

```
# index.js
import "@webcomponents/custom-elements/src/native-shim.js";
// NB rest of file after native-shim import
```

**Comment by nqthqn** [comment]
@opsb nice. I will check that out :)

**Comment by halfzebra** [comment]
It looks like this is no longer an issue, co I'm closing this.

Please feel free to reopen it if you have further comments!
