### ISSUE TITLE
Dev server is trying to proxy a CSS file in public dir

### ISSUE THREAD

**Issue by GAumala** [halfzebra/create-elm-app#253]
### Is this a bug report?

Yes

### Environment

node: v10.0.0
yarn: 1.6.0
create-elm-app: 1.10.4

OS: Arch Linux

### Steps to Reproduce

1. Set a proxy in `elm-package.json`
2. Add a single stylesheet to `public`, something like `public/style.css`
3. Link to that stylesheet in `public/index.html` with `<link rel="stylesheet" href="%PUBLIC_URL%/style.css">`
4. Run `elm-app start`

### Expected Behavior

I expected the requests to files in `public` to not be proxied, and the dev server should serve those files without any extra configuration.

### Actual Behavior

The stylesheet is not served because the request to the stylesheet in `public` is being proxied every single time.

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by halfzebra** [comment]
Should be fixed in #284 

Please let me know if this is still a problem.
