### ISSUE TITLE
Travis CI timeout

### ISSUE THREAD

**Issue by Jbarget** [halfzebra/create-elm-app#261]
Has anyone else used CI with create-elm-app?

We have an elm app served by an express server that is struggling to pass CI on Travis due to timeout. Im pretty sure its due to the same issues found in https://github.com/elm/compiler/issues/1473

Since the above thread work mostly talks about `elm make` and `elm test`, should the `sysconfcpus` fix work for a `create-elm-app` project that calls `elm-app build` and `elm-app test`?

Here's an example of our failed travis build: https://travis-ci.org/RegSimple/FrontEndRegSimple/jobs/388688681

Any help would be absolutely great!

**Comment by halfzebra** [comment]
Hello @Jbarget, thanks for reporting the issue!

After checking the Travis CI log you have shared, I think this particular error is not coming from `elm test` or Create Elm App.

Please check out this example of a project using Create Elm App with tests on Travis CI https://github.com/halfzebra/drinking-game-for-web-devs/blob/master/.travis.yml

I'd recommend checking the User Guide section on using [Continuous Integration,
](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#continuous-integration) in case if you are not following the guide.

Please let us know if you are still experiencing the issue.

**Comment by Jbarget** [comment]
thanks @halfzebra, all worked great 👍

**Comment by halfzebra** [comment]
Happy to hear that, thanks for the feedback! 🙂
