### ISSUE TITLE
Add Javascript testing for ports

### ISSUE THREAD

**Issue by MarcCoquand** [halfzebra/create-elm-app#266]
Hello,

First thank you for developing this great tool! The only thing that I really miss is a way to easily integrate create-elm-app with Jest so that you can also test your Ports and ensure that the Javascript code is correct.

**Comment by halfzebra** [comment]
Hello @MarcCoquand, I'm afraid for now we are not going to include another test runner into the existing set of tools.

I suspect that the best course would be creating a documentation section explaining the steps required for adding Jes.

Please let me know what you think.

**Comment by halfzebra** [comment]
I feel like there was not enough interest in this feature.

I'll close this issue for now, but please feel free to comment if you have future suggestions! 🙌
