### ISSUE TITLE
Question: How to deploy to sites like Netlify?

### ISSUE THREAD

**Issue by timojaask** [halfzebra/create-elm-app#274]
Create Elm App makes it super easy to get started and build Elm apps. That's awesome for people like me how are just getting started.

However, I can't figure out how do I use it in a third-party CI environment, for example, on https://www.netlify.com, where normally you'd just point it to a git repository, and it just fetches the code, runs a build command that's defined in your `package.json` file, e.g. `yarn build`, and pushes to production.

Since `elm-app` is not generally available on such services (I'm assuming), how can I make it work?

**Comment by littleStudent** [comment]
1. create your own package.json. 
2. install create-elm-app as dependency
3. use create-elm-app directly to build OR use your ‘npm build’ step to do it
4. thats it 🙌. if your build step outputs a usable build folder you are good to go

**Comment by timojaask** [comment]
That's awesome, thanks for the instructions! 🙌

**Comment by halfzebra** [comment]
@littleStudent maybe you are interested in adding a section to the [User Guide](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#deployment)?

**Comment by halfzebra** [comment]
Closing this one, since it's covered by the [User Guide](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#netlify) 

Thanks to @littleStudent :+1:

**Comment by ModestMC** [comment]
This popped up for me on google while trying to figure out how to deploy an elm site using netlify, so I'm leaving this here for anyone else who tries what I did.

Netlify can have its build configuration specified to use elm make (currently it uses v 0.19.0), but if you want to do something closer to what the original poster was asking about [Elm Pages](https://elm-pages.com/) might be a good choice. They have a fork template button on their github to make it easy.
