### ISSUE TITLE
elm-app start returned undefined

### ISSUE THREAD

**Issue by hpb0412** [halfzebra/create-elm-app#286]
### Is this a bug report?

I am not sure!!

### Environment

1. `node -v`: 8.9.0
2. `npm -v`:
3. `yarn --version` (if you use Yarn): 1.7.0
4. `npm ls create-elm-app -g` (if you haven’t ejected): 2.0.2

Then, specify:

1. Operating system: Mac HighSierra 10.13.6
2. Browser and version (if relevant):
3. Elm version: 0.19-bugfix2

### Steps to Reproduce

(Write your steps here:)

1. install create-elm-app by `sudo yarn global add create-elm-app@2.0.2`
2. create a test project by `create-elm-app test`
3. run develop mode by `elm-app start`

### Expected Behavior

Should start dev server at `localhost:3000`

### Actual Behavior

Nothing happened. Just show `undefined`

<img width="552" alt="screen shot 2018-09-05 at 5 16 27 pm" src="https://user-images.githubusercontent.com/7277539/45087286-8784b280-b12f-11e8-870b-409f0458baf0.png">

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by berry** [comment]
On Macbook Pro, Mac OS 10.13.6
Elm installed via pkg-installer from elm-lang.org

npm install create-elm-app@2.0.2 -g -> elm-app start -> "undefined"
npm install create-elm-app@2.0.1 -g -> elm-app start -> "undefined"
npm install create-elm-app@2.0.0 -g -> elm-app start -> code compiles and dev-server is started.

**Comment by hpb0412** [comment]
Thank @halfzebra, confirm fixed at 2.0.3.
Thanks for fast response :)
