### ISSUE TITLE
Version 2.0.0 breaks travis build

### ISSUE THREAD

**Issue by Jbarget** [halfzebra/create-elm-app#288]
### Is this a bug report?

Yes

### Environment

1. `node -v`: v8.11.2
2. `npm -v`: 5.6.0
3. `yarn --version` (if you use Yarn):
4. `npm ls create-elm-app -g` (if you haven’t ejected): 2.0.0

Then, specify:

1. Operating system: Mac OSx
2. Browser and version (if relevant):

### Steps to Reproduce

Our .tavis.yml has the line `npm i create-elm-app -g` under the install target
https://github.com/RegSimple/FrontEndRegSimple/blob/staging/.travis.yml

### Expected Behavior

Travis to be able to run the elm tests

### Actual Behavior
Travis suddenly started failing at the point at which `elm-app` was called.
https://travis-ci.org/RegSimple/FrontEndRegSimple/builds/424225031

### Reproducible Demo

https://travis-ci.org/RegSimple/FrontEndRegSimple/builds/424225031

**Comment by halfzebra** [comment]
Hi @Jbarget, thanks for the effort to report this issue!

You will not be able to use Create Elm App v2 as it is intended to be used with Elm 0.19.

Please upgrade your client with [elm-upgrade](https://github.com/avh4/elm-upgrade) and hopefully you'll be happy to enjoy the features landing soon #280 

I'm closing this issue, but please feel free to comment or reopen if you feel like it.
