### ISSUE TITLE
What should I do to use ports?

### ISSUE THREAD

**Issue by Mazuh** [halfzebra/create-elm-app#294]
> elm-reactor does not work with apps that rely on ports.

So, no `app.ports`? 🤔 This phrase is quite simple but ins't very clear, and I'm not getting `ports` to work here on my application bootstrapped with `create-elm-app`, it's always throwing errors due to `.ports` be `undefined`. If I'm write, I think would be nice to add the answer to my question on the docs/readme.

**Comment by littleStudent** [comment]
Hi @Mazuh, is this the information you need?
https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#javascript-interop

**Comment by halfzebra** [comment]
Hi @Mazuh, thanks for asking the question here!

Please check the documentation recommended by @littleStudent, it is updated to `0.19` and will hopefully help you setup ports in your app.

I'll close this issue for now, but please feel free to reopen it if you are experiencing other issues setting up ports.
