### ISSUE TITLE
https://github.com/elm-explorations/test

### ISSUE THREAD

**Issue by bifunctor** [halfzebra/create-elm-app#296]
Hi    

Does elm-explorations/test is integrated into create-elm-app? Or is still using https://github.com/elm-community/elm-test?   

Thanks

**Comment by halfzebra** [comment]
Hi @bifunctor!

Thanks for your question, both packages you are referring to are the same package, which is used by Create Elm App.

I hope this helps!

**Comment by bifunctor** [comment]
Thanks a lot
