### ISSUE TITLE
Can't compile after upgrading to 2.0.3 due to assets size

### ISSUE THREAD

**Issue by thiagorp** [halfzebra/create-elm-app#297]
After upgrading to the version `2.0.3` I started getting the following error on my CI:

![image](https://user-images.githubusercontent.com/571864/45759801-00eccc80-bc29-11e8-9d49-9a0b40c5ab57.png)

I use an [external css template](https://tabler.github.io/tabler/) and have little control of the file size of the css. I tried following the code-splitting hint of webpack but it requires a [plugin](https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import/#installation) that I cannot install unless a eject this library.

Is there any other way of solving it? My initial thought was hosting the external css file in a CDN and loading it on my index.html file, but I am strngly trying to avoid it.

**Comment by halfzebra** [comment]
Hi @thiagorp!

Thanks for reporting this issue, I'm afraid the culprit is somewhere else since those are just warnings from Webpack.

I have disabled them in #299 

Please try upgrading to 2.0.4 and tell me if that changes anything.

**Comment by thiagorp** [comment]
Hi @halfzebra!

Thank you for this great tool 😄

Ah great! I read somewhere that those were the changes needed. I will try the 2.0.4 version out and let you know as soon as do.

**Comment by thiagorp** [comment]
Just as extra information: I only reported this here because the "no warnings on CI" comes from `create-elm-app` and there is no way around it. Also there was no way to configure webpack to ignore the performance tips.

**Comment by thiagorp** [comment]
@halfzebra I just tested and it works now. Thank you very much.
