### ISSUE TITLE
Creating new elm-app does not work on Windows

### ISSUE THREAD

**Issue by pydevil** [halfzebra/create-elm-app#303]
### Is this a bug report?
I guess so. 
I've read related issues but didn't help. I've tried reinstall all - npm, node, elm, create-elm-app.

### Environment
1. `node -v`: v8.11.4
2. `npm -v`: 5.6.0
3. `yarn --version` (if you use Yarn):
4. `npm ls create-elm-app -g` (if you haven’t ejected): 
`C:\Users\pydev\AppData\Roaming\npm
`-- create-elm-app@2.0.5`

Then, specify:

1. Operating system: Windows 10
2. Browser and version (if relevant): 

### Steps to Reproduce
`create-elm-app exampleapp`

### Expected Behavior
Created new elm-app

### Actual Behavior

`Creating exampleapp project...
Failed to install elm packages
Please, make sure you have internet connection!
In case if you are running Unix OS, you might look in to this issue:

    https://github.com/halfzebra/create-elm-app/issues/10`

**Comment by halfzebra** [comment]
Hi @pydevil!

Thanks for reporting this!

What happens if you run `npx elm make src\Main.elm` ?

**Comment by pydevil** [comment]
`Success! Compiled 1 module.`
I've checked that, despite of not successful warning, the project is actually created and it's running after `elm-app start`
