### ISSUE TITLE
ELM_DEBUGGER=true doesn't work when building apps, because it collides with --optimize

### ISSUE THREAD

**Issue by runarfu** [halfzebra/create-elm-app#304]
### Is this a bug report?

Yes

### Environment

1. `node -v`: v10.9.0
2. `npm -v`: 6.2.0
3. `yarn --version` (if you use Yarn): 1.9.4
4. `npm ls create-elm-app -g` (if you haven’t ejected):
~/.nvm/versions/node/v10.9.0/lib
└── create-elm-app@2.0.5

Then, specify:

1. Operating system: Ubuntu
2. Browser and version (if relevant): N/A

### Steps to Reproduce

1. Successfully build an app with `elm-app build`.
2. Verify that the app is running without the time travel debugger.
3. Enable the debugger according to the [docs](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#turning-onoff-elm-debugger): `$ ELM_DEBUGGER=true elm-app build`.

### Expected Behavior

A successful build, with the debugger enabled.

### Actual Behavior

It fails like this:
```
$ ELM_DEBUGGER=true elm-app build
Creating an optimized production build...
Failed to compile.

./src/Main.elm
-- CLASHING FLAGS --------------------------------------------------------------

I cannot compile with --optimize and --debug at the same time.

I need to take away information to optimize things, and I need to add
information to add the debugger. It is impossible to do both at once, so pick
just one of those flags.
```

### Reproducible Demo
N/A

**Comment by halfzebra** [comment]
Hi @runarfu, thanks for reporting this!

Would you like to work on a PR?

**Comment by runarfu** [comment]
@halfzebra I've opened a PR which seems to solve this issue :)
