### ISSUE TITLE
Add documentation for `configureWebpack` in elmapp.config.js

### ISSUE THREAD

**Issue by andys8** [halfzebra/create-elm-app#316]
Feature to be able to overwrite webpack configuration was added with https://github.com/halfzebra/create-elm-app/commit/92b5308 and needs to be documented as discussed in comment https://github.com/halfzebra/create-elm-app/commit/92b5308#commitcomment-31058897

```js
module.exports = {
  configureWebpack: (config, env) => {
    // mutate the config object and return it.
    return config;
  }
}
```

**Comment by halfzebra** [comment]
Hi @andys8!

Thanks for reporting this issue, the documentation was added to the [User Guide](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#overriding-webpack-config), please let us know if you feel like something is missing.
