### ISSUE TITLE
Using object for proxy configuration no longer works

### ISSUE THREAD

**Issue by caseyhoward** [halfzebra/create-elm-app#326]
### Is this a bug report?

Yes

### Environment

1. `node -v`: v10.12.0
2. `npm -v`: 6.4.1
3. `yarn --version` (if you use Yarn): 1.12.3
4. `npm ls create-elm-app -g` (if you haven’t ejected):
/usr/local/lib
`-- (empty)

Then, specify:

1. Operating system: Linux Mint 19.1 (using nodejs docker container)
2. Browser and version (if relevant):
N/A

### Steps to Reproduce

Create an elmapp.config.js file with the proxy setting set to an object

1. Open elmapp.config.js
2. Add the following:
  "proxy": {
    "/api": { target: "http://localhost:3001" }
   },
3. Save file
4. Run "elm-app start"

### Expected Behavior

App starts without error. I have tried this with create-elm-app 2.2.0 and it still works fine. However, the latest version does not.

### Actual Behavior

The following error is outputted and the server doesn't start:
```
When specified, "proxy" in package.json must be a string.
Instead, the type of "proxy" was "object".
Either remove "proxy" from package.json, or make it a string.
```

**Comment by halfzebra** [comment]
There's a release candidate available under the `next` tag, which addresses this :tada: 

Please check it out:

```
npm i create-elm-app@next
```

The docs are available [here](https://github.com/halfzebra/create-elm-app/tree/d4a91e13314061655f0ae1e385bdd1a3b2f6201e/template#configuring-the-proxy-manually).

Please let me know what you think!

**Comment by kornicameister** [comment]
@halfzebra thx a lot. I will definitely look into it next day (or rather today, in my TZ)
