### ISSUE TITLE
Can not get `setupProxy` running - manual proxy setup

### ISSUE THREAD

**Issue by kornicameister** [halfzebra/create-elm-app#331]
@halfzebra so I tried doing what documentation suggests but it seems like `setupProxy` defined as property of `module.exports` is not being called :(. Although the file itself is picked up as I could spot the `console.log` I've put in there. 

Here's my `elmapp.config.js`:

```
const proxy = require('http-proxy-middleware');

// modify at your convenience
const env = 'https://my.proxy.env';

console.log('I have been loaded - elmapp.config.js')
module.exports = {
  setupProxy: function(app) {
    console.log('I am not called :(', proxy, env)
    app.use(proxy('/api', { target: env, secure: false }));
  }
};
```

and this might also be important:
```
  "devDependencies": {
    "check-node-version": "^3.2.0",
    "concurrently": "^4.1.0",
    "create-elm-app": "^3.0.0",
    "elm-format": "^0.8.1",
    "file-loader": "^2.0.0",
    "http-proxy-middleware": "^0.19.1",
    "node-sass-chokidar": "^1.3.4",
    "prettier": "1.15.3",
    "spdy-transport": "^3.0.0",
    "tslint": "^5.11.0",
    "webpack": "^4.27.1"
  },
```

**Comment by halfzebra** [comment]
Hello Tomasz! Thank you for your feedback, I will look into this shortly.

**Comment by halfzebra** [comment]
Hello again, this should be fixed in `v3.0.1`!

Please let me know if you are experiencing any more issues :raised_hands: 

Closing this for now, please feel free to reopen if anything.

**Comment by kornicameister** [comment]
@halfzebra works like a charm now! cheers!

**Comment by halfzebra** [comment]
Thanks for the feedback! :open_hands:
