### ISSUE TITLE
`elm app test watch`

### ISSUE THREAD

**Issue by jackfranklin** [halfzebra/create-elm-app#34]
Would be a really useful command to add. I'd love to take a stab at it if you're open to the idea?

**Comment by halfzebra** [comment]
Thanks for another good idea @jackfranklin 👍 

You are very welcome to send a PR

My best shot would be to try [chokidar](https://github.com/paulmillr/chokidar) or even [chokidar-cli](https://github.com/kimmobrunfeldt/chokidar-cli) for the starters, but I'm not sure.

**Comment by halfzebra** [comment]
I have good and bad news.

It looks like [rtfeldman/node-test-runner](https://github.com/rtfeldman/node-test-runner) supports file watching [already](https://github.com/rtfeldman/node-test-runner/commit/9def5ff7942218d52296005e288abe91f955745c#diff-a9fdbb49f32181e82baf5d2d40812e23)

This will probably make #40 obsolete.

**Comment by jackfranklin** [comment]
That's good news! So do we need to update the elm app CLI to pass flags through to test ?

**Comment by halfzebra** [comment]
@jackfranklin yes, it should do something similar to what we're doing to all other `elm-platform` cli commands.

Just one tricky thing, we want `elm-test` to use the compiler from the `create-elm-app` as it [is done here already](https://github.com/halfzebra/create-elm-app/blob/master/bin/global-cli.js#L33)

Probably, we should proxy all the flags, except `--compiler`

**Comment by halfzebra** [comment]
#59 closes this one!
