### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by FranzSkuffka** [halfzebra/create-elm-app#340]
https://github.com/dkodaj/impfix has worked for me on a lot of files with just one error. This would be a killer feature. I now do not need to waste time anymore finding unused imports to clear circular dependencies.

`elm-app remove-unused-imports`

**Comment by kornicameister** [comment]
This tool is for `elm 0.18`. Why not using `elm-analyse` or `elm-lsp`? Both of these can be integrated or are already integrated in tooling available for `Vim`, `VSCode` or `Atom`? I am personally using `Neovim + ale + elm-lsp` and it works great, actively displaying unused imports and not only that.

**Comment by FranzSkuffka** [comment]
The tool has worked for me perfectly fine on a ~10k codebase of elm 0.19 code.

I am not using any of these editors, I am using `kakoune`. I prefer to have an editor that is not overloaded with plugins and integrations. `elm-lsp` is a language server and `elm-analyse` is a general purpose tool. I do not see any of them solving the problem of obsolete circular dependencies with a line of code and within two seconds.

**Comment by kornicameister** [comment]
I might remember it incorrectly, I haven't stumbled upon this for a long time. But AFAIR Elm does not compile if there's a circular dependency, right? If there's one and it happens to be not used you will remove it anyway :). 

---

`elm-lsp` runs `elm-analyse` under the hood and apart from showing unused imports it show unused exports. But I assume you already know this :).

**Comment by FranzSkuffka** [comment]
I think our workflows differ vastly - Probably I need to take a leaf out of your book there.

**Comment by kornicameister** [comment]
Might be just that :). Anyway, there is one good thing that came out of this. This editor you mentioned seems really nice.

**Comment by halfzebra** [comment]
Hello Franz!

While I completely agree with the motivation for this improvement, it doesn't look like the tool is being actively maintained. I've decided to close this issue for now.

Please let me know if you have further suggestions or questions!

**Comment by FranzSkuffka** [comment]
Hey Ed!

I am actively using this tool and I would maintain it if necessary. However it was stable for the last year and works perfectly on several k LOC. It has saved me days. I'm not super fussed though because I just add scripts to my package.json doing the job.
