### ISSUE TITLE
Upgrade to elm 0.19.0-bugfix6

### ISSUE THREAD

**Issue by anagrius** [halfzebra/create-elm-app#342]
### Is this a bug report?

No

Is there any good reason not to upgrade to Elm 0.19.0-bugfix6?

**Comment by halfzebra** [comment]
Hey Thomas!

Thanks for raising the awareness. Tere's no reason to not to update!
Would you like to make a PR? 🙂

**Comment by halfzebra** [comment]
I'm happy to close this issue, the latest version contains this update!

Took me some time  to track down the issues with `elm-test` :sweat:
