### ISSUE TITLE
Suggestion: Do not register SW by default, 99% of the time it's not needed

### ISSUE THREAD

**Issue by olpeh** [halfzebra/create-elm-app#345]
I feel it's kind of weird to add a service worker by default. 

Most of the projects don't need service workers and they will only create additional problems, especially for developers who don't know about SWs, how they work, and how they should be used.

Those who know they need a service worker, will for sure figure out how to add it.

**Comment by halfzebra** [comment]
Hi Olavi!

Thank you for your feedback, I think this makes a lot of sense! ServiceWorker could be super annoying sometimes and we've been considering making it optional for some time.

It will become optional in the next major release 👍

**Comment by halfzebra** [comment]
Hello Olavi and @fpapado, Service Workers are now disabled by default!

Thanks for raising the awareness for this issue! 👍
