### ISSUE TITLE
Comment in `Tests.elm` references wrong `elm-test` package

### ISSUE THREAD

**Issue by atomanyih** [halfzebra/create-elm-app#348]
This line:
https://github.com/halfzebra/create-elm-app/blob/1d9418128ba4535bff33e48192a05c18174dff5e/template/tests/Tests.elm#L7
Does not match this:
https://github.com/halfzebra/create-elm-app/blob/04ec73d9af4f77cf09d52bd7978ec9e5aad9ea68/template/elm.json#L20

Should probably reference: https://package.elm-lang.org/packages/elm-explorations/test/latest

**Comment by halfzebra** [comment]
Good catch! Would you like to make a PR with a fix?

**Comment by halfzebra** [comment]
Hello August!

Thanks for reporting this, the issue has been fixed in the latest release!
