### ISSUE TITLE
Keep elm-package.json and tests/elm-package.json in sync

### ISSUE THREAD

**Issue by jackfranklin** [halfzebra/create-elm-app#35]
I often forget that I need to install the dependencies in two places if something that's under test needs the module that I just installed. I wonder if we could include an install command that simply runs elm package install in both locations?

**Comment by halfzebra** [comment]
Technically it is possible to intercept `elm-app package install` command and run `elm-package install` in both places.

It's a good idea, but I'm not sure how easy it is to achieve the reliable sync between those.

**Comment by jackfranklin** [comment]
Yeah I'm also not sure how much of a good idea it is in practice. It's a shame that this is how most Elm apps are structured. I wonder if anyone else has solved this problem.

**Comment by halfzebra** [comment]
@jackfranklin technically, there's no reason to keep two `elm-package.json` files in the project, maybe it's possible to use just one in the root? I haven't had time to look in to [rtfeldman/node-test-runner](https://github.com/rtfeldman/node-test-runner), but it might be doable.

**Comment by halfzebra** [comment]
@jackfranklin there's a similar issue [elm test init should copy dependencies](https://github.com/rtfeldman/node-test-runner/issues/68)

**Comment by halfzebra** [comment]
Okay, I have ported it [elm-deps-sync](https://github.com/halfzebra/elm-deps-sync), it's not on npm yet, but I think I will give a shot at integrating it in to  [rtfeldman/node-test-runner](https://github.com/rtfeldman/node-test-runner), since they have the same issue and if I solve it there, I'll solve it here 😆

**Comment by jackfranklin** [comment]
This is really cool! Would you just run it when the tests run?

**Comment by halfzebra** [comment]
@jackfranklin apparently this is already implemented in [node-test-runner/issues/68](https://github.com/rtfeldman/node-test-runner/issues/68)

**Comment by jackfranklin** [comment]
Nice! That's awesome.
