### ISSUE TITLE
Cannot install with Node 12

### ISSUE THREAD

**Issue by xlport** [halfzebra/create-elm-app#356]
### Is this a bug report?

Yes:

Running `npm i -g create-elm-app` fails

### Environment

1. `node -v`: v12.2.0
2. `npm -v`: 6.9.0
3. `npm ls create-elm-app -g` (if you haven’t ejected): N/A
4. Operating system: Windows 10

### Steps to Reproduce
* Use Node v12.2.0
* Run `npm i -g create-elm-app`

### Expected Behavior

Succesful installation

### Actual Behavior

```
[...]
> binwrap-install

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\PeterAlbert\AppData\Roaming\npm\node_modules\create-elm-app\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\PeterAlbert\AppData\Roaming\npm\node_modules\create-elm-app\node_modules\natives\index.js:55:10)
[....]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.19.0 install: `binwrap-install`
npm ERR! Exit status 1
[...]
```

This seems to be a problem with the `unzip` dependency, see [this issue for instance](https://github.com/mafintosh/prebuildify-ci/issues/5)

As this happens on Windows, using `nvm` to switch to v11 is not an option unfortunately.

**Comment by xlport** [comment]
I investigated this further - the root cause is the package `"elm": "^0.19.0"`, referenced in "elm-webpack-loader". Looks like this [PR](https://github.com/elm-community/elm-webpack-loader/pull/173) would solve it...

**Comment by xlport** [comment]
Here's the underlying issue: https://github.com/elm-community/elm-webpack-loader/issues/170

**Comment by halfzebra** [comment]
Hello @xlport!

Thank you for reporting this, I've been looking into this issue in the loader for some time.
It might be a little slow with releases during the summer, so I went ahead and updated it directly in CEA dependencies.

Long story short, the issue should be resolved for now 🙂 

Please feel free to reopen this if you have further questions.
