### ISSUE TITLE
Way to change localhost port

### ISSUE THREAD

**Issue by MoonlightOwl** [halfzebra/create-elm-app#36]
How can I change `elm-app start` default port value?
(:3000 is already occupied with another service, so I can't run my Elm app.)

**Comment by halfzebra** [comment]
Thanks for the contribution, this is totally a must!

I think it should be possible to specify the port by using `-p` or `--port` flag.

Also we need a better error, when port is occupied.

**Comment by BKSpurgeon** [comment]
@Montycarlo Thank you Josh that was perfect.
