### ISSUE TITLE
elm-app test fails on alpine and nixos

### ISSUE THREAD

**Issue by snewell92** [halfzebra/create-elm-app#365]
Hello friends!

Is [this fix from node-test-runner](https://github.com/rtfeldman/node-test-runner/pull/358) in the [latest release](https://www.npmjs.com/package/create-elm-app/v/3.2.1) of CEA? I'm starting a little app and [getting my GitLab CI setup](https://gitlab.com/sNewell/trakr/-/jobs/270884681) but am running into what I _think_ is a fixed issue. I'm just running my tests with `elm-app test` and I have gotten elm-app from running `npm i -g create-elm-app`. I'm also seeing this locally on my NixOS machine.

Does the node test runner just need a new release cut over in npm? It looks like it got a new release after the fix was merged in master, but when I install it locally `npm i -g elm-test` I get the same error on my NixOS machine. I can comment at the end of the linked PR to ask.

An easy repro is just trying to run `elm-app test` in an alpine container and seeing if you get the same error my linked CI job got.

**Comment by halfzebra** [comment]
Hi Sean!

I might be wrong, but it seems like this fix was never released to NPM.
I'd recommend raising the awareness in the original repo.

Otherwise, you can install `elm-test` directly from GitHub to fix this.
Please let me know if you have further comments or questions.
