### ISSUE TITLE
Deployment to heroku

### ISSUE THREAD

**Issue by halfzebra** [halfzebra/create-elm-app#37]
I want to be able to deploy apps, but unfortunately I don't have that much experience with making build-packs.

There is a pretty cool project [HappyAndHarmless/heroku-buildpack-elm](https://github.com/HappyAndHarmless/heroku-buildpack-elm), let's see if it's possible to have the setup for deployment on Heroku in template.

**Comment by fobos** [comment]
I have small experience with [12 factor apps](https://12factor.net) and deploying to heroku. let me know if I can help

**Comment by halfzebra** [comment]
@fobos sounds cool, I would be more than happy to get any help, since I haven't touched deployment tools for ages 😄

If you have any ideas on how we could get a simple deployment setup for newly created apps, please share!

**Comment by fobos** [comment]
I'm starting to work on it.

**Comment by halfzebra** [comment]
@fobos  Awesome! 👍

**Comment by gyzerok** [comment]
It seems like keeping tool as small as possible would be much better then explode it with infinite new features. What do you think?

**Comment by halfzebra** [comment]
@gyzerok you are absolutely right! This issue is more about adding some guidelines than making an automated deployment.

**Comment by halfzebra** [comment]
I'm closing this issue, it looks a bit out of scope for this project.

I'm still pretty open to the idea of adding the Heroku deployment guidelines to the User Guide. 

@fobos please feel free to reopen or create a new issue if you still feel like this deserves more attention.

**Comment by fobos** [comment]
@halfzebra i'm totally agree with @gyzerok and you.

**Comment by chemmi** [comment]
If anyone is still interested in some boilerplate to deploy on Heroku: [chemmi/heroku-create-elm-app](https://github.com/chemmi/heroku-create-elm-app)

It is not (yet) a full buildpack though. I use the inline buildpack to build the app and nodejs to install create-elm-app.
