### ISSUE TITLE
elm and elm-test dependency versions are incompatible

### ISSUE THREAD

**Issue by sentience** [halfzebra/create-elm-app#379]
### Is this a bug report?

Yes.

### Environment

1. `node -v`: v10.11.0
2. `npm -v`: 6.4.1
3. `yarn --version` (if you use Yarn): 1.9.4
4. `npm ls create-elm-app -g` (if you haven’t ejected): 
```
/Users/kyank/.asdf/installs/nodejs/10.11.0/.npm/lib
└── create-elm-app@3.2.2
```

Then, specify:

1. Operating system: macOS 10.14.6
2. Browser and version (if relevant): n/a

### Steps to Reproduce

1. `npm install -g create-elm-app` (installs elm 0.19.0 and elm-test 0.19.1 as dependencies)
2. (In a fresh clone of a pre-existing project:) `npm install`
3. `elm-app test`

### Expected Behavior

Expected tests to run.

### Actual Behavior

Error message:

```
-- ELM VERSION MISMATCH ----------------------------------------------- elm.json

Your elm.json says this application needs a different version of Elm.

It requires 0.19.1, but you are using 0.19.0 right now.

Compilation failed while attempting to build /Users/kyank/Downloads/front-end-coding-test/tests/Tests.elm
```

### Reproducible Demo

Hopefully not necessary, but if creating a blank project with a single test in it would help, let me know!

**Comment by halfzebra** [comment]
Thanks for the feedback! :+1: 

I think this is no longer an issue with the latest release.
Please feel free to reopen this if you have further questions.
