### ISSUE TITLE
Configurable webpack-dev-server Proxy

### ISSUE THREAD

**Issue by halfzebra** [halfzebra/create-elm-app#38]
I would like to be able to run the development server with [Proxy](https://webpack.github.io/docs/webpack-dev-server.html#proxy)

Probably this configuration should go in to `elm-package.json`

**Comment by selasiehanson** [comment]
@halfzebra, Any progress on proxy feature?

**Comment by halfzebra** [comment]
@selasiehanson, unfortunately, this one is not planned for the next release. Would you like to work on a PR?

**Comment by Aash-Kothari** [comment]
@halfzebra I'm using a proxy by setting it in the `elm-package.json` and this is working fine only on the dev server. When I created build by using `elm-app build` then proxy stops working on the production server. Can you please suggest me any solution to resolve this.

**Comment by halfzebra** [comment]
Hello @Aash-Kothari, the proxy is only intended for development purposes.

The actual proxy requires a running a server that will proxy the requests, I'd suggest looking into [node-http-proxy](https://github.com/nodejitsu/node-http-proxy)
