### ISSUE TITLE
Link broken in src/registerServiceWorker.js

### ISSUE THREAD

**Issue by MartinSStewart** [halfzebra/create-elm-app#380]
The `src/registerServiceWorker.js` file that's generated by create-elm-app has the following comment
```
// To learn more about the benefits of this model, read https://goo.gl/KwvDNy.
// This link also includes instructions on opting out of this behavior.
```
but unfortunately the link leads to a "page not found" on Github.

**Comment by FranzSkuffka** [comment]
Well I can not reproduce this. I do end up https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app and from there I go to here:https://create-react-app.dev/docs/making-a-progressive-web-app/

**Comment by halfzebra** [comment]
Thanks for the feedback! 👍 

I'll close this as the link is not dead. Pleae feel free to reopen this if you have further questions.

**Comment by MartinSStewart** [comment]
Works for me too. I guess the link was fixed in the time between reporting it and now.
