### ISSUE TITLE
Move elm-asset-webpack-loader to dependencies

### ISSUE THREAD

**Issue by andys8** [halfzebra/create-elm-app#382]
Hey @halfzebra 

Webpack dependencies are normally dev dependencies. But in the case of `create-elm-app`: Does it need a to be a normal dependency? I think so...
(Couldn't try it so far)

https://github.com/halfzebra/create-elm-app/blob/fcbaa17785f930fde28bf4df833f5501f3799ac7/package.json#L74

## slack quote

![Screenshot_20191106-115534](https://user-images.githubusercontent.com/13085980/68292547-68afe200-008c-11ea-958a-16b600f5ea05.png)

**Comment by halfzebra** [comment]
Good point, it's kinda hard to catch this kind of regression without reworking the test setup.

Thanks for fixing this! 👍

**Comment by andys8** [comment]
Sorry for the trouble and thanks for the quick release :)

By the way, we could [use it the example template](https://github.com/halfzebra/create-elm-app/compare/master...andys8:improvement/example-with-elm-asset-webpack-loader) but I'm not sure if it's the best idea. For beginners this type of custom syntax is maybe solving a problem they don't have.
