### ISSUE TITLE
Feature request : Provide different templates

### ISSUE THREAD

**Issue by Tarektouati** [halfzebra/create-elm-app#384]
### Is this a bug report?

No, just a feature request.

Hi, maybe we could provide more templates to users, like Elm apps with navigation pre-configured and up and running. 
Also bootstrap the project with `package.json` with some useful scripts like : 
```json
"scripts": {
    "build": "elm-app build",
    "start": "elm-app start",
    "make": "elm make",
    "repl": "elm repl",
    "reactor": "elm reactor",
    "test": "elm-test"
  }
```
Thanks.

**Comment by jangerhard** [comment]
Hi,

The command elm-app already has these built-in:

```
Usage: elm-app <command>

where <command> is one of:
    build, start, test, eject, repl, init, reactor, make, install, bump, diff, publish
```

You can also initialize your own `package.json` and use custom commands.

**Comment by Tarektouati** [comment]
Hi @jangerhard .
This feature request is more about including `package.json` file at the root directory of the project generated by `create-elm-app`. with these scripts set in it. 
And maybe to add some boilerplate, to more easily setup SPA, etc ...
