### ISSUE TITLE
elm-app start --no-debug

### ISSUE THREAD

**Issue by eimfach** [halfzebra/create-elm-app#392]
Hey there,

I found no option for this. I want to run my elm app without dev tools. I am creating large stacks of Msg's dynamically and am working with large lists (3000+ length). After a lot of investigation, the dev tools seem to be a huge bottleneck for me ...

**Comment by halfzebra** [comment]
Hi Robin!

Thanks for your feedback! 👍 

There is a way to run your app without the devtools:

```bash
ELM_DEBUGGER=false elm-app start
```

It's a good idea to introduce a flat to contol this, would you like to work on a PR?

**Comment by eimfach** [comment]
Thanks ! :) I wasn't aware of this...

Yes, I can work on that. Could you give me a hint on where to start, or a brief overview of what needs to be done ?

**Comment by halfzebra** [comment]
I think the easiest is to add a new `if` statement in https://github.com/halfzebra/create-elm-app/blob/master/bin/elm-app-cli.js#L48, which would check for `--no-debug` flag to be present in arguments passed to the command.

The simplest way to start is to fork this repo and try logging `argv` variable while running `node bin/elm-app-cli.js --no-debug`

Then you can set `process.env.ELM_DEBUGGER` to be `false`, which would do the trick.

It would also be nice to have the documentation about the flag mentioned somewhere.

How does that sound?

**Comment by eimfach** [comment]
Hi Eduard,
I implemented it, but can't test it because `npm run app:start` is failing resolving the polyfill modules and some others:

```
../config/polyfills.js
Module not found: Can't resolve 'object-assign' in '/workspaces/create-elm-app/config'

../scripts/utils/webpackHotDevClient.js
Module not found: Can't resolve 'sockjs-client' in '/workspaces/create-elm-app/scripts/utils'

../scripts/utils/webpackHotDevClient.js
Module not found: Can't resolve 'strip-ansi' in '/workspaces/create-elm-app/scripts/utils'
```

**Comment by halfzebra** [comment]
Thanks for the heads-up! I haven't seen this kind of error before, but it looks like something is trying to run `scripts/utils/webpackHotDevClient.js` 

I think it's best if you could open a PR, I will try to debug it.
What do you think?

**Comment by eimfach** [comment]
Maybe you should just install those dependencies and save them as dev dependencies in the package.json ? Are those dependencies for a running 'elm-create-app' project instance ? I am not sure where they are coming from when a project gets initialized, however I think it does make sense for Webpack just run its expected configuration (as it is), when running `npm run app:start`. For me it looks just how it should behave, except that the modules are missing. So I added them via `--save-dev` and now it runs.

**Comment by halfzebra** [comment]
Thanks for reporting this issue!

I'll see if the dependencies will become a problem, for now I'll keep it as it is. Have a nice weekend! :raised_hands:
