### ISSUE TITLE
Cannot npm install package

### ISSUE THREAD

**Issue by Samuelote** [halfzebra/create-elm-app#394]
I'm getting an error trying to run `sudo npm install create-elm-app -g` on linux:

ERR { Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/create-elm-app/node_modules/elmi-to-json/unpacked_bin'

Any ideas?

**Comment by halfzebra** [comment]
Hi Samuel!

NPM is known for having permission issues when installing globally on UNIX.

Here are the possible solutions:
- [Resolving EACCES permissions errors when installing packages globally](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)
- Using [Node Version Manager](https://github.com/nvm-sh/nvm), which uses a better place for installing Node and packages effectively solving the problem

Let me know if this is helpful!

**Comment by halfzebra** [comment]
Feel free to re-open this if you have further questions!
