### ISSUE TITLE
Hot Reload Throws Exception on Updating the Browser

### ISSUE THREAD

**Issue by mickeyvip** [halfzebra/create-elm-app#43]
Version `0.1.8`

After changing something and saving the file, the hot reload updates the page, but with an error:

![image](https://cloud.githubusercontent.com/assets/220427/20081192/9a0ab4f4-a556-11e6-8c14-eac8532052c9.png)

Workaround: additional manual refresh settles the things.

**Comment by halfzebra** [comment]
This is fixed! 😑
