### ISSUE TITLE
Error when dependency uses .mjs

### ISSUE THREAD

**Issue by wolfadex** [halfzebra/create-elm-app#438]
### Is this a bug report?

Yes

### Environment

1. `node -v`: v12.16.1
2. `npm -v`: 6.14.4
3. `yarn --version` (if you use Yarn): 1.22.4
4. `npm ls create-elm-app -g` (if you haven’t ejected): create-elm-app@4.2.12

Then, specify:

1. Operating system: Chrome OS and OS X
2. Browser and version (if relevant):
    - firefox: version, v75.0 (64-Bit)
    - chrome: Version 81.0.4044.103 (Official Build) (64-bit)

### Steps to Reproduce

(Write your steps here:)

1. Add dependency `npm i cached-iterable`
2. Import in `index.js `import { CachedSyncIterable } from 'cached-iterable';`
3. App fails to compile.

### Expected Behavior

App should build and `CachedSyncIterable` should be defined.

### Actual Behavior

![image](https://user-images.githubusercontent.com/1542461/80324506-566a6180-87ee-11ea-9795-6a3bb667b308.png)

### Reproducible Demo

https://github.com/wolfadex/mjs-bug-example

### Other:

[This PR](https://github.com/wolfadex/fluent-web/pull/18) was opened in response to using `create-elm-app` with a package that uses `.mjs` file extensions.

I additionally tested both `@wolfadex/fluent-web` and `cached-iterable` with `create-react-app` and a custom built app and didn't run into any issues. The custom built project had a `package.json` of

```json
{
  "scripts": {
    "dev": "webpack-dev-server"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.5",
    "babel-loader": "^8.1.0",
    "html-webpack-plugin": "^4.2.0",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  },
  "dependencies": {
    "cached-iterable": "^0.3.0"
  }
}
```
a webpack config of

```js
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
	mode: "development",
	entry: "./src/index.js",
	module: {
		rules: [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				use: {
					loader: "babel-loader"
				}
			}
		]
	},
  	plugins: [new HtmlWebpackPlugin()]
}
```
and an `index.js` of

```js
import { CachedSyncIterable } from "cached-iterable";

console.log("carl", CachedSyncIterable)

const carl = CachedSyncIterable.from([1, 2, 3]);

console.log("steve", carl)
```

The project built and `CachedSyncIterable` was defined.

**Comment by halfzebra** [comment]
Hi Wolfgang!

Thanks for reporting this issue! 👍

To be honest I kind of hoped that this would be solved by #358 

I'll have a look to find out whether I can do anything about this, but in a while I can point out a possible solution https://github.com/halfzebra/create-elm-app/issues/352#issuecomment-490867828
