### ISSUE TITLE
Non-zero exit code in case of build fail

### ISSUE THREAD

**Issue by MoonlightOwl** [halfzebra/create-elm-app#44]
Currently, `elm-app build` command always returns zero code, even if the build was failed.
Like [here](https://travis-ci.org/hel-repo/hel-face/builds/172234665).

It may be very helpful for auto-deploy configuration, if it will return non-zero code when fails.

**Comment by fobos** [comment]
@halfzebra 
I have investigated the problem and know solution. Will make a PR shortly.

**Comment by halfzebra** [comment]
@fobos could you please share some background on that? It seems like there's problem with updated dependencies.

**Comment by fobos** [comment]
@halfzebra We should check exit code from child process and pass it to main process if it is non zero
