### ISSUE TITLE
`npm test` runs globally installed package instead of local

### ISSUE THREAD

**Issue by fobos** [halfzebra/create-elm-app#45]
I have globally installed previous version (`0.1.6`) of package.
Just have cloned repo with latest source. Have installed all packages.

Trying to run tests via `npm test`. Tests failed:
```
  Test command line interface functionality
    CLI accessibility
      ✓ `create-elm-app` command should be available (156ms)
      ✓ `elm-app` command should be available (130ms)
      ✓ `elm-app package` command should be available (150ms)
    Create Elm application with `create-elm-app` command
      ✓ `create-elm-app test-app` should succeed (1368ms)
      ✓ `test-app` should have elm-package.json file
      ✓ `test-app` should have .gitignore file
      1) `test-app` should have the same file structure as template
    Building Elm application with `elm-app build`
      ✓ `elm-app build` should succeed in `test-app` (4677ms)
    Ejecting Elm application
      ✓ `elm-app eject` should succeed in `test-app` (45405ms)
      ✓ Ejected application should have `package.json` with scripts from Create Elm App
      ✓ Ejected application should have build and start scripts
      ✓ Ejected application should have the config available
      ✓ It should be possible to build ejected applitaction, using npm scripts (7655ms)
```

In test code I see next line `var status = spawn.sync('create-elm-app', [ testAppName ]).status;`
It's give me idea that code tries to run globally installed package.

P.S. As I understand, `0.1.6` setups `dist` folder  by running `create-elm-app` command while `0.1.8` doesn't.

**Comment by halfzebra** [comment]
@fobos good catch!

> It's give me idea that code tries to run globally installed package.

Yes and no, I'm using [npm link](https://docs.npmjs.com/cli/link) in [.travis.yml](https://github.com/halfzebra/create-elm-app/blob/master/.travis.yml#L8)

There's no reason to rely on globally linked package, when running tests!

`npm test` should run tests without any setup, except `npm install`

**Comment by fobos** [comment]
@halfzebra how do you run tests locally?

>There's no reason to rely on globally linked package, when running tests!
npm test should run tests without any setup, except npm install

Surely

**Comment by halfzebra** [comment]
@fobos I have `create-elm-app/` folder linked using `npm link` all the time.

That's why I've done it the way it is right now. I've thought it would make sense, since I will be able to test the availability of cli commands and the functionality, using just one set of tests.

I'm open to any ideas with improvements for tests!

**Comment by fobos** [comment]
@halfzebra I will think about how it can be refactored for simpler workflow.

**Comment by halfzebra** [comment]
@fobos actually, I have an idea.

To test command availability, we should have a separate test, which will only test available commands, exposed by the module(and maybe assert some expected output to stdout). This test will will be only executed on test server.

The other test will be testing the functionality, when running `npm test` and just spawn `node scriptname.js --args` so it does not require global installation.

How does that sound?

**Comment by fobos** [comment]
@halfzebra You describe the way I'm using now :) 
I'm going to work on the tests this weekend and show you few related PRs. Ok?

**Comment by halfzebra** [comment]
@fobos sweet!

Then let's have it that way! 💪
