### ISSUE TITLE
Make isolated tests

### ISSUE THREAD

**Issue by fobos** [halfzebra/create-elm-app#47]
Right now most of tests depends on result of `'Create Elm application with `create-elm-app` command'` suite. It is very uncomfortable to run separate test.

Can make a PR for it.

**Comment by halfzebra** [comment]
@fobos I'm totally up for removing the dependency. How would you do it?

PR's are very welcome! 😃

**Comment by fobos** [comment]
@halfzebra 
>PR's are very welcome! 

Going to make it.
