### ISSUE TITLE
Add more practical information to User Guide

### ISSUE THREAD

**Issue by halfzebra** [halfzebra/create-elm-app#5]
The User Guide must give practical advice on:
- Further development;
- Deployment (GitHub Pages, Heroku);
- Ejecting, and evolving the build.

**Comment by peterszerzo** [comment]
I find the deployment guides for `create-react-app` a bit on the overly verbose side. How about keeping it snappy and adding a couple of shell commands for deployment? For `Surge`, for instance:

`npm i -g surge`
`surge login`
`elm-app build`
`cp dist/index.html dist/200.html` (if using pushstate)
`surge ./dist hostingdomain.com`
Look [here](surge.sh) for more details.

**Comment by halfzebra** [comment]
I'm closing this issue, the scope has changed.

Deployment to GitHub Pages was added.

The rest is not relevant for the CEA User Gude at the moment.
