### ISSUE TITLE
npm ERR! Refusing to delete /usr/local/bin/elm-app:

### ISSUE THREAD

**Issue by manuscrypt** [halfzebra/create-elm-app#57]
I got the following when doing `sudo npm update -g create-elm-app`.
Moving the file as suggested solved it, tho.

23960 verbose stack Error: Refusing to delete /usr/local/bin/elm-app: ../lib/node_modules/create-elm-app/bin/global-cli.js symlink target is not controlled by npm /usr/local
23960 verbose stack     at clobberFail (/usr/share/npm/lib/utils/gently-rm.js:162:12)
23960 verbose stack     at isSafeToRm (/usr/share/npm/lib/utils/gently-rm.js:152:15)
23960 verbose stack     at /usr/share/npm/lib/utils/gently-rm.js:93:5
23960 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:7:26)
23960 verbose stack     at /usr/share/npm/node_modules/slide/lib/chain.js:18:7
23960 verbose stack     at skipENOENT (/usr/share/npm/lib/utils/gently-rm.js:174:38)
23960 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:11:16
23960 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:11:16
23960 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:11:16
23960 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:11:16
23961 verbose cwd /home/mb/code/elm
23962 error Linux 4.4.0-45-generic
23963 error argv "/usr/bin/nodejs" "/usr/bin/npm" "update" "-g" "create-elm-app"
23964 error node v4.2.6
23965 error npm  v3.5.2
23966 error path /usr/local/bin/elm-app
23967 error code EEXIST
23968 error Refusing to delete /usr/local/bin/elm-app: ../lib/node_modules/create-elm-app/bin/global-cli.js symlink target is not controlled by npm /usr/local
23969 error File exists: /usr/local/bin/elm-app
23970 error Move it away, and try again.
23971 verbose exit [ 1, true ]

**Comment by halfzebra** [comment]
@manuscrypt Thanks for the contribution!

I'm aware of this problem, but unfortunately I can't offer any other solution than removing the file 😢

**Comment by manuscrypt** [comment]
I had a feeling. No problem at all. Thank you for the awesome tool!

**Comment by fobos** [comment]
@halfzebra I think it's exists since I made #53
