### ISSUE TITLE
Enable historyApiFallback: true in create-elm-app

### ISSUE THREAD

**Issue by jackfranklin** [halfzebra/create-elm-app#63]
If you work with elm-lang/navigation or any similar tools, going to `localhost:3000/foo` will break as Webpack dev server tries to serve that file.

If we set `historyApiFallback: true` as an option when booting the dev server, this works as expected. I think this makes a sensible default - or at the least I'd love to be able to configure it without having to eject.

WDYT?

**Comment by halfzebra** [comment]
@jackfranklin I totally agree on this one, it would be a good addition to existing functionality.

Would you like to work on PR?

**Comment by jackfranklin** [comment]
👍 incoming!

**Comment by jackfranklin** [comment]
Done as of #64 :)
