### ISSUE TITLE
Problems creating a new app

### ISSUE THREAD

**Issue by AliceCH** [halfzebra/create-elm-app#67]
I am having getting this error when trying to create a new app with create-elm-app

```
sujaira@sujaira-desktop:~/test-job/elm-test$ create-elm-app my-app

Creating my-app project...


Failed to install elm packages

Please, make sure you have internet connection!

In case if you are running Unix OS, you might look in to this issue:

    https://github.com/halfzebra/create-elm-app/issues/10
```
but I don't have any problem with my internet connection. 
I run elm-package install in my-app folder and after installing the packages I run elm-app start but I am getting this error

Failed to compile.

```
Error in ./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/create-elm-app/node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm-make ENOENT
 @ ./src/index.js 3:10-31 
```

what could be causing this errors ?

**Comment by halfzebra** [comment]
@AliceCH you have to install the module with:

```sh
sudo npm install create-elm-app -g
```

**Comment by AliceCH** [comment]
I did installed it and I didn't get any errors during installation, yet I can't create an app. I tried updating the versions for node and npm. But I keep getting the same error.

**Comment by halfzebra** [comment]
@AliceCH [elm-platform](https://github.com/elm-lang/elm-platform) installer has failed to install the binaries, this will not throw any errors, because elm-platform installer does not [check for permissions](https://github.com/elm-lang/elm-platform/issues/164)

The same problem appears on Linux.

The only solution I'm aware of, is using `sudo` to install Create Elm App with root privileges.

**Comment by AliceCH** [comment]
I had installed Create Elm App with sudo, and I still can't get pass the error.

**Comment by j-panasiuk** [comment]
It may also be possible that this is related to old nodejs version
I had identical symptoms after upgrading to Elm 0.18 - create-elm-app stopped working for me (as did similar tools like elm-live). Eventually it turned out that I was still on node 4.6 and after upgrade to latest version (7.2.1) everything went back to normal

**Comment by pzingg** [comment]
I'm having the same problem with elm 0.18.0, node 7.4.0, on Ubuntu Mint 18.1. Have re-installed 

```
sudo npm install -g elm
sudo npm install -g create-elm-app
```

Could it be the Ubuntu Mint version?

**Comment by j-panasiuk** [comment]
I don't think that Mint version 18 vs 18.1 has anything to do with it (at least would be very surprised).
This error seems to happen when script fails to download elm binaries.
On Linux Mint I would expect them to sit inside `/usr/lib/node_modules/create-elm-app/node_modules/elm` folder. If the **Elm-Platform** folder is empty or missing, you can try to run install.js script by hand
```
sudo npm run install
```
In my case this worked https://github.com/halfzebra/create-elm-app/issues/26

**Comment by halfzebra** [comment]
I'm closing this issue, please feel free to reopen it if you are still experiencing this problem.

**Comment by rmoorman** [comment]
I have been able to install en use create-elm-app on Linux Mint (based on Ubuntu bionic 18.04) without using sudo (luckily) ... I just had to fiddle with some npm/node related settings/environment variables as decribed [here](https://topaxi.codes/use-npm-without-root-or-sudo-rights/) or [here](https://devin-clark.com/global-npm-install-without-sudo.html)
