### ISSUE TITLE
Clearing console is slightly weird on MacOS

### ISSUE THREAD

**Issue by halfzebra** [halfzebra/create-elm-app#7]
Terminal on MacOS is not being cleared.

Currently it uses:

``` js
function clear () {
  console.log('\x1Bc');
}
```

There must be a better way to do this.

**Comment by fobos** [comment]
What's wrong with it?

**Comment by halfzebra** [comment]
@fobos it preserves the whole stdout, while on Win you can flush the entire content. It seems like expected behaviour.

I'm closing this issue for now.
