### ISSUE TITLE
Publishing with gh-pages

### ISSUE THREAD

**Issue by halfzebra** [halfzebra/create-elm-app#70]
It would be nice to have a simple workflow for publishing an app with [gh-pages](https://www.npmjs.com/package/gh-pages)

Maybe this could be automated as a script for `elm-app`.

**Comment by fobos** [comment]
I think about this feature in case of #37

**Comment by halfzebra** [comment]
@fobos personally I don't like prompts in the terminal and use `-y, --yes` where possible.
Since I'm biased, I think it's your call to decide on that 😄 

@jackfranklin do you have an opinion on prompts?

**Comment by jackfranklin** [comment]
I think I'd rather run `elm app deploy --github` or `elm app deploy --gh-pages` - an API like that makes most sense to me but happy to take the majority opinion!

Much like Eduard I use `-y` nearly always when working with `elm package` and related tools.

**Comment by fobos** [comment]
@jackfranklin totally agree with you.

**Comment by newswim** [comment]
How is it going with this feature? I saw blog post today that demonstrates a pretty simple deployment, using a `--orphan` branch.

https://jasonneylon.wordpress.com/2015/11/08/quickly-create-github-io-pages-for-your-elm-projects

**Comment by halfzebra** [comment]
@newswim it's possible to deploy your apps to GitHub Pages, please have a look at the relevant Guide section [Guide section](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#deploying-to-github-pages)

I'm closing this issue for now, please feel free to leave a comment if you think something is missing.

**Comment by oaalto** [comment]
Hi,
I've tried the what the guide says, but there seems to be a problem with the way create-elm-app generates the paths for the css and js links in the index.html file.

If you go to https://oaalto.github.io/ShoppingList/ and check the network you can see that the resources are fetched with an URL like this https://oaalto.github.io/static/css/main.6cc19a18.css when it should be like this https://oaalto.github.io/ShoppingList/static/css/main.6cc19a18.css

create-elm-app puts forward slashes at the beginning of the both links. 

In my package.json I have:
"homepage": "https://oaalto.github.io/ShoppingList/"

create-elm-app@1.2.0

**Comment by halfzebra** [comment]
@oaalto the `"homepage"` is supposed to be in `elm-package.json`, the original non-ejected version does not have `package.json`.

I hope this helps!

**Comment by oaalto** [comment]
Yes, now it works. Thanks!

The guide should probably be updated to reflect the fact that the "homepage" needs to be in elm-package.json and not in package.json.

**Comment by mahidul-islam** [comment]
gh-pages 3.11 gives an error like :
The “path” argument must be of type string. Received undefined
downgrading to 2.0 solves it. 
what is the problem
