### ISSUE TITLE
Add `beginnerProgram` and `program` templates

### ISSUE THREAD

**Issue by mickeyvip** [halfzebra/create-elm-app#8]
Thank you for this tool!

Currently the tool generates most basic `Hello World` program, that does not follow the Elm Architecture.

It would be great to have on option(s) to generate a skeleton for `Html.App.beginnerProgram` as well as `Html.App.program` as a starting point.

The following examples can be used:
https://guide.elm-lang.org/architecture/user_input/buttons.html
https://guide.elm-lang.org/architecture/effects/http.html (**The Bare Minimum**)

**Comment by halfzebra** [comment]
Thank you for your contribution!

I'm totally up for adding a better starting point.

A bit concerned about different types of `Program`, because having a template per every type sounds like a dangerous idea.

What do you say about having `Html.App.program` with established life-cycle, as the default starting point?

If we will have many templates, how would you control switching between them?

**Comment by julianjelfs** [comment]
I really agree that this would be a great addition, The first thing I did after bootstrapping my new app was add the standard, View.elm, Update.elm, Types.elm and use Html.App.program. I think this will be a really common scenario and it would be great to have a way to support it out of the box. 

This has already made life so much easier though - great work!

**Comment by mickeyvip** [comment]
@halfzebra, `Html.App.program` being a default option will be really great in my opinion.

Although this should be **the** starting point for a serious Elm application, I think having an option to create `Html.App.beginnerProgram` will also be very convenient.

Maybe `create-elm-app` can have command line switches?

`$ create-elm-app my-cool-app`
`$ create-elm-app my-cool-beginner-app --beginner`

**Comment by joakin** [comment]
As another note, I found the current generated sources great as they are minimal and let me choose how to continue.

**Comment by joakin** [comment]
Adding those documentation links to the README.md and maybe in a comment in Main.elm would be a great addition IMO.

> The following examples can be used:
> https://guide.elm-lang.org/architecture/user_input/buttons.html
> https://guide.elm-lang.org/architecture/effects/http.html (The Bare Minimum)

**Comment by mickeyvip** [comment]
Found similar project with different options for creating a new project like I had suggested [here](https://github.com/halfzebra/create-elm-app/issues/8#issuecomment-248110278).
https://github.com/simonewebdesign/elm-new

**Comment by halfzebra** [comment]
As of today, I'm not sure if `create-elm-app` should cover every possible use-case.

Current template offers `Html.App.program` by default, and I think it should work with `Navigation.program`, but I'd prefer to wait for `0.18.0` for that.

PR's are very welcome, but I'm not sure if I will have time to work on that.

**Comment by mickeyvip** [comment]
@halfzebra, I like the new template with `Html.App.program` and separation of `Main.elm` from `App.elm`!

With that I have few minor suggestions:

*  we can move the hard coded message to the `Model`, thus using the `model` in the App.
* we can add at least 1 test that involves our `model`, thus making the test more "real"/"relevant".

Thank you.

**Comment by halfzebra** [comment]
@mickeyvip good thinking! this was my original plan when adding tests, but then I have realised, that there's nothing to test in the `App.elm` at the moment. Please share your ideas, if you have any!

I'm not quite sure, what you mean by:

> we can move the hard coded message to the Model, thus using the model in the App.

Could you please rephrase that?

**Comment by mickeyvip** [comment]
in `App.elm`:

```elm
view : Model -> Html Msg
view model =
    div [] [ text "Your Elm App is working!" ]
```

I meant to move `"Your Elm App is working!"` to be a part of the `Model`.

```elm
type alias Model =
    { message : String }

init : ( Model, Cmd Msg )
init =
    ( { message = "Your Elm App is working!" }, Cmd.none )

view : Model -> Html Msg
view model =
    div [] [ text model.message ]
```

**Comment by mickeyvip** [comment]
Just noticed another thing - after changing something and saving the file, the hot reload updates the page, but with an error:

![image](https://cloud.githubusercontent.com/assets/220427/20081192/9a0ab4f4-a556-11e6-8c14-eac8532052c9.png)

Not sure if it's something local on my PC.

**Comment by mickeyvip** [comment]
@halfzebra, same JavaScript exception is happening on Mac.

![image](https://cloud.githubusercontent.com/assets/220427/20087644/23d2fbb6-a583-11e6-9ee8-4d8914f2d198.png)

Should I open another issue?

**Comment by halfzebra** [comment]
@mickeyvip please, create an issue. There's a problem with some of the dependencies. The latest stable version is `0.1.6` for now.

**Comment by mickeyvip** [comment]
Created https://github.com/halfzebra/create-elm-app/issues/43

**Comment by halfzebra** [comment]
@mickeyvip I like the idea with a message in the model, would you like to send a PR?

**Comment by mickeyvip** [comment]
Created PR https://github.com/halfzebra/create-elm-app/pull/49

**Comment by halfzebra** [comment]
I'm closing this issue for now, thanks for participating to @mickeyvip @joakin

Please leave feedback if you think something is missing.
