### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by halfzebra** [halfzebra/create-elm-app#83]
Since now we have automated semantic release, it would be great to establish some guidelines for contributing.

**Comment by halfzebra** [comment]
I have added the initial info for contributors, please comment on this issue or open a new one if you have any suggestions or ideas.

**Comment by peterszerzo** [comment]
Might it be a good idea to link to the [create-react-app contributing guide](https://github.com/facebookincubator/create-react-app/blob/master/CONTRIBUTING.md)? They do a really nice job explaining things like limiting configuration and relying on heuristics. I also think that a one-liner 'Thanks for contributing, we look forward to seeing your pull requests' could encourage people to hop on board quicker.

Happy to make these changes if you see them fit, @halfzebra.

**Comment by halfzebra** [comment]
@peterszerzo good idea!

Please send a PR! :+1:
