### ISSUE TITLE
Initialise git repo on create

### ISSUE THREAD

**Issue by jackfranklin** [halfzebra/create-elm-app#86]
Maybe? I tend to like my boilerplates to do a "First commit from create-elm-app" git commit so a repo is all set up for me, but that might just be because I'm lazy!

**Comment by halfzebra** [comment]
@jackfranklin Thanks for sharing the idea!

How would you go about this?

**Comment by jackfranklin** [comment]
Just after all the files are set up and everything has been installed, I'd run `git init && git commit -m "Project created (from create-elm-app)"` or something.

**Comment by halfzebra** [comment]
Sorry @jackfranklin, but it looks like this feature is a bit too specific.

I'm going to close this issue for now, but I'm pretty open to discuss this idea, so feel free to reopen it if anything.
