### ISSUE TITLE
Set up testing by default

### ISSUE THREAD

**Issue by jackfranklin** [halfzebra/create-elm-app#9]
We could use elm-test to set up some basic testing by default. WDYT? I'm happy to work on a PR if you like the idea :)

**Comment by halfzebra** [comment]
Hello!

Thanks for the contribution!

My initial ambition was to provide the experience of using Elm, without any npm dependencies for the app itself(I'm not sure if that's the right way to do it)

I have omitted testing setup intentionally, to make it easier for newcomers to focus on the code.

If you were to integrate [rtfeldman/node-test-runner](https://github.com/rtfeldman/node-test-runner/tree/2.0.1), how would you do it?

What do you say about integrating [rtfeldman/node-test-runner](https://github.com/rtfeldman/node-test-runner/tree/2.0.1), so users don't have to maintain `package.json` in their Elm apps?

I'm open to any ideas 😄

**Comment by giulioungaretti** [comment]
Just my feelings coming from pure ignorance, the less npm the easier, but having testing out of box sounds actually amazing

**Comment by jackfranklin** [comment]
I would definitely use node-test-runner, because we can maybe piggyback onto it's `elm-test init` function and mean that we get most of it all set up for free.

It would be a shame to have to include a `package.json`, I agree, but I think by setting some tests up we encourage people to use them. In addition, because the tests are largely in the `tests` directory, they are easily removed if people want them to be.

You can see how I usually have these set up by checking out https://github.com/jackfranklin/elm-boilerplate :)

**Comment by halfzebra** [comment]
@jackfranklin we can take [rtfeldman/node-test-runner](https://github.com/rtfeldman/node-test-runner/tree/2.0.1), and proxy cli commands to `elm-test` through `elm-app test` for non-ejected apps.

When app is ejected, then it's a regular `npm run test`

How doe that sound?

**Comment by jackfranklin** [comment]
Sounds good to me. So initially when the app is created we would call `elm-test init` behind the scenes to create those files? Or shall we just mirror them in this app as templates?

And then there's a new `elm-app test` which just proxies through up until the point at which you eject? :)

**Comment by halfzebra** [comment]
@jackfranklin what is your opinion on that?

I wanted to avoid keeping `elm-package.json` in template, but now I'm not sure if it's necessary.

Running `elm-test init` would be a good starting point.

When [#8](https://github.com/halfzebra/create-elm-app/issues/8) is done, I think it would be nice to write a real test, which tests something from the dummy app.

**Comment by halfzebra** [comment]
Testing setup is available since [0.1.6](https://github.com/halfzebra/create-elm-app/tree/0.1.6) 👏

**Comment by jackfranklin** [comment]
Wicked! Sorry I never got round to working on it :(

**Comment by halfzebra** [comment]
@jackfranklin It's cool, thanks for contribution to the discussion!

Too much stuff to do and not enough time 😃
