### ISSUE TITLE
Not working with yarn

### ISSUE THREAD

**Issue by gyzerok** [halfzebra/create-elm-app#90]
When trying to install as a global dependency with yarn package do not work

```
$ elm-app --help
module.js:327
    throw err;
    ^

Error: Cannot find module '../node_modules/elm/package.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/fnez/.config/yarn/global/node_modules/create-elm-app/bin/elm-app-cli.js:9:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by halfzebra** [comment]
@gyzerok thank you for the contribution!

I've looked into that, but unfortunately I can't tell what is the problem (for now).

I'll give it another shot later this week.

**Comment by gyzerok** [comment]
Just a wild guess: maybe `yarn.lock` is ignored in npm distribution while it shouldn't be?

**Comment by lrosa007** [comment]
I got this issue today. To be fair I did some funky thing earlier where I had uninstalled npm by accident with `yarn global remove npm`. I just wanted to see what would happen. Anyways, it was resolved by going into where `create-elm-app` was installed and manually running `npm install`.

**Comment by danielmartinprieto** [comment]
Hi! FYI, I had the same issue as well today, I've updated Yarn this morning (working in other things) and running `elm-app start` tonight wasn't working. I've _fixed_ it using @lrosa007's solution.

**Comment by halfzebra** [comment]
@danielmartinprieto thanks for the feedback! Please don't hesitate to provide more details, if there's a problem with Create Elm App, we would love to get it fixed 🙂

**Comment by danielmartinprieto** [comment]
Thanks to you for this awesome tool.

I was using Yarn before and I installed the tool with it, and everything worked. This morning I remember updating Yarn to the latest version (which is, btw, a major change, v1.0.1, coming from 0.28.X). This evening I couldn't start the app.

Let me know how I can help you further with the problem.
