### ISSUE TITLE
Project stopped building correctly after 0.2.1 to 0.2.4 update

### ISSUE THREAD

**Issue by MoonlightOwl** [halfzebra/create-elm-app#94]
Just updated `create-elm-app` tool, and found that after building, resulting `dist` folder does not contain one of two images. 
For some reasons, it just stopped adding `logo.png` in my build:
```
Hash: a04a29783dd15daf70f6
Version: webpack 1.14.0
Time: 9928ms
                          Asset       Size  Chunks             Chunk Names
static/media/about.6c5ea71c.png      14 kB          [emitted]  
            js/main.81a8a9e3.js     271 kB       0  [emitted]  main
          css/main.bfc7ed41.css     154 kB       0  [emitted]  main
                    favicon.ico  521 bytes          [emitted]  
                     index.html    1.16 kB          [emitted]  

```
This is my project: https://github.com/hel-repo/hel-face
And this is how my images are attached to the project:

```js
<...>
require('./Images/about.png');
require('./Images/logo.png');

var Elm = require('./Main.elm');

var root = document.getElementById('root');

Elm.Main.embed(root);
```

(https://github.com/hel-repo/hel-face/blob/master/src/index.js)

Everything works okay on `0.2.1`:
```
Hash: 26a581f82038620448fb
Version: webpack 1.13.3
Time: 16834ms
                          Asset       Size  Chunks             Chunk Names
static/media/about.6c5ea71c.png      14 kB          [emitted]  
 static/media/logo.7c5853e0.png    8.59 kB          [emitted]  
            js/main.562a2cfd.js     259 kB       0  [emitted]  main
          css/main.bfc7ed41.css     154 kB       0  [emitted]  main
Compiled successfully!
```

**Comment by halfzebra** [comment]
@MoonlightOwl thank you for reporting a bug!

I have investigated the issue, [webpack/url-loader](https://github.com/webpack/url-loader) is embedding images under 10Kb into the bundle as a base64 string.

```
var logo = require('./Images/logo.png');

// pass logo into Elm App as a flag and use this base64 in src to add an image
```

It is slightly confusing, but it might be a pretty good optimization in some cases.

**Comment by Rolograaf** [comment]
How can you update an existing project? Is there a special command, or can i download and just overwrite all files?

**Comment by halfzebra** [comment]
@Rolograaf Could you please explain what do you mean exactly by updating the project?

**Comment by Rolograaf** [comment]
Create-elm-app is now at release 0.3.0 but when i started my project is was some releases before that. Can i just reinstall it?

**Comment by halfzebra** [comment]
@Rolograaf yes, just install it one more time. NPM will download the latest version and you will be able to use it with your app.

**Comment by MoonlightOwl** [comment]
@halfzebra yeah, it is a good optimization. So, I decided to use flags.

By the way, [url-loader](https://github.com/webpack-contrib/url-loader) readme says, that I can use additional parameter to tweak size limit like this:
```js
require("url-loader?limit=10000!./file.png");
// => DataUrl if "file.png" is smaller than 10kb
```
Is it possible to use such parameters with `create-alm-app`?

**Comment by halfzebra** [comment]
@MoonlightOwl Yes, you can use [the configuration query to alter loaders behavior](https://webpack.js.org/loaders/svg-inline-loader/#example-usage)

Please feel free to reopen this issue if you are still experiencing the problem with the latest version.
